# Generated by Django 5.2.12 on 2026-03-16 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=32, unique=True, verbose_name='Номер')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('department', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критичный')], default='medium', max_length=16, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('on_hold', 'Ожидание'), ('resolved', 'Выполнена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='new', max_length=24, verbose_name='Статус')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('closure_confirmed', models.BooleanField(default=False, verbose_name='Закрытие подтверждено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_workorders', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workorders', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workorders', to='inventory.medicaldevice')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workorders/%Y/%m/%d/')),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Комментарий к заявке',
                'verbose_name_plural': 'Комментарии к заявке',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTransitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('on_hold', 'Ожидание'), ('resolved', 'Выполнена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], max_length=24)),
                ('to_status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('on_hold', 'Ожидание'), ('resolved', 'Выполнена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'Переход заявки',
                'verbose_name_plural': 'Переходы заявок',
                'ordering': ['-created_at'],
            },
        ),
    ]
