# Generated by Django 5.2.12 on 2026-03-18 06:38

from django.db import migrations, models


def create_default_columns(apps, schema_editor):
    KanbanColumnConfig = apps.get_model("workorders", "KanbanColumnConfig")
    defaults = [
        ("new", "Новые", 10, ["new"]),
        ("in_progress", "В работе", 20, ["accepted", "in_progress", "on_hold"]),
        ("done", "Выполнены", 30, ["resolved"]),
        ("archive", "Архив", 40, ["closed", "cancelled"]),
    ]
    for code, title, position, statuses in defaults:
        KanbanColumnConfig.objects.update_or_create(
            code=code,
            defaults={
                "title": title,
                "position": position,
                "statuses": statuses,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workorder_closure_confirmed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanColumnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('statuses', models.JSONField(default=list, verbose_name='Статусы')),
            ],
            options={
                'verbose_name': 'Колонка канбана',
                'verbose_name_plural': 'Колонки канбана',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RunPython(create_default_columns, migrations.RunPython.noop),
    ]
