# Generated by Django 5.2.12 on 2026-03-18 10:45

from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_departments(apps, schema_editor):
    Department = apps.get_model("core", "Department")
    WorkOrder = apps.get_model("workorders", "WorkOrder")

    department_map = {}
    for raw_name in WorkOrder.objects.order_by().values_list("department", flat=True).distinct():
        normalized = (raw_name or "").strip()
        if not normalized:
            continue
        department, _ = Department.objects.get_or_create(name=normalized, parent=None)
        department_map[normalized.lower()] = department.id

    for workorder in WorkOrder.objects.all():
        normalized = (workorder.department or "").strip()
        if normalized:
            workorder.department_ref_id = department_map[normalized.lower()]
            workorder.save(update_fields=["department_ref"])


def backwards_copy_departments(apps, schema_editor):
    WorkOrder = apps.get_model("workorders", "WorkOrder")

    for workorder in WorkOrder.objects.select_related("department_ref"):
        if workorder.department_ref_id:
            workorder.department = workorder.department_ref.name
            workorder.save(update_fields=["department"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("workorders", "0003_kanbancolumnconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="department_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.department",
                verbose_name="Подразделение",
            ),
        ),
        migrations.RunPython(forwards_copy_departments, backwards_copy_departments),
        migrations.RemoveField(
            model_name="workorder",
            name="department",
        ),
        migrations.RenameField(
            model_name="workorder",
            old_name="department_ref",
            new_name="department",
        ),
        migrations.AlterField(
            model_name="workorder",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workorders",
                to="core.department",
                verbose_name="Подразделение",
            ),
        ),
    ]
