# Generated by Django 5.2.12 on 2026-03-18 15:30

from django.db import migrations


def backfill_human_numbers(apps, schema_editor):
    WorkOrder = apps.get_model("workorders", "WorkOrder")
    for workorder in WorkOrder.objects.order_by("pk"):
        workorder.number = f"{workorder.pk:06d}"
        workorder.save(update_fields=["number"])


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0004_department_reference"),
    ]

    operations = [
        migrations.RunPython(backfill_human_numbers, migrations.RunPython.noop),
    ]
