# Generated by Django 5.2.12 on 2026-03-18 16:10

from django.db import migrations


def normalize_workorder_numbers(apps, schema_editor):
    WorkOrder = apps.get_model("workorders", "WorkOrder")
    for workorder in WorkOrder.objects.order_by("pk"):
        normalized = str(workorder.pk)
        if workorder.number != normalized:
            workorder.number = normalized
            workorder.save(update_fields=["number"])


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0005_backfill_human_numbers"),
    ]

    operations = [
        migrations.RunPython(normalize_workorder_numbers, migrations.RunPython.noop),
    ]
