# Generated by Django 5.2.12 on 2026-04-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_workorder_device_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanbancolumnconfig',
            name='wip_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 - без лимита', verbose_name='WIP Лимит'),
        ),
    ]
