# Generated by Django 5.2.12 on 2026-04-23 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workorders', '0008_kanbancolumnconfig_wip_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancolumnconfig',
            name='code',
            field=models.SlugField(verbose_name='Код'),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='allowed_boards', to='auth.group', verbose_name='Разрешенные группы')),
            ],
            options={
                'verbose_name': 'Канбан-доска',
                'verbose_name_plural': 'Канбан-доски',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='kanbancolumnconfig',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='workorders.board', verbose_name='Доска'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='workorders.board', verbose_name='Доска'),
        ),
        migrations.AlterUniqueTogether(
            name='kanbancolumnconfig',
            unique_together={('board', 'code')},
        ),
    ]
