# Generated by Django 5.2.12 on 2026-05-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0011_make_board_non_nullable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kanbancolumnconfig',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='kanbancolumnconfig',
            constraint=models.UniqueConstraint(fields=('board', 'code'), name='unique_board_code'),
        ),
    ]
