# Generated by Django 5.2.12 on 2026-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0012_alter_kanbancolumnconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='resolved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('on_hold', 'Ожидание'), ('resolved', 'Выполнена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], db_index=True, default='new', max_length=24, verbose_name='Статус'),
        ),
    ]
