# Generated by Django 5.2.12 on 2026-05-15 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_department_unique_together_and_more'),
        ('inventory', '0005_alter_medicaldevice_is_archived_and_more'),
        ('workorders', '0013_add_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('on_hold', 'Ожидание'), ('resolved', 'Выполнена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], default='new', max_length=24, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['-updated_at', '-created_at'], name='workorders__updated_957346_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='workorders__status_2e2089_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority'], name='workorders__priorit_226700_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assignee'], name='workorders__assigne_818f49_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['resolved_at'], name='workorders__resolve_bebe61_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['closed_at'], name='workorders__closed__c8f261_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['closure_confirmed'], name='workorders__closure_47a5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderattachment',
            index=models.Index(fields=['content_type'], name='workorders__content_a87152_idx'),
        ),
        migrations.AddIndex(
            model_name='workordercomment',
            index=models.Index(fields=['author'], name='workorders__author__e3b439_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertransitionlog',
            index=models.Index(fields=['from_status'], name='workorders__from_st_2bb41d_idx'),
        ),
        migrations.AddIndex(
            model_name='workordertransitionlog',
            index=models.Index(fields=['to_status'], name='workorders__to_stat_4d05ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('rating__gte', 1), ('rating__lte', 5)), ('rating__isnull', True), _connector='OR'), name='workorder_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closure_confirmed', False), ('closure_confirmed_at__isnull', True)), models.Q(('closure_confirmed', True), ('closure_confirmed_at__isnull', False)), _connector='OR'), name='workorder_closure_confirmed_consistent'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('resolved_at__isnull', False), ('status__in', ['resolved', 'closed'])), ('status__in', ['new', 'accepted', 'in_progress', 'on_hold', 'cancelled']), _connector='OR'), name='workorder_resolved_at_consistent'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', False), ('status', 'closed')), ('status__in', ['new', 'accepted', 'in_progress', 'on_hold', 'resolved', 'cancelled']), _connector='OR'), name='workorder_closed_at_consistent'),
        ),
    ]
