# Generated by Django 5.2.12 on 2026-05-28 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_medicaldevice_is_archived_and_more'),
        ('workorders', '0014_alter_workorder_resolved_at_alter_workorder_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancolumnconfig',
            name='wip_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 - без лимита', verbose_name='Лимит в работе'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_workorders', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workorders', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыто'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workorders', to='inventory.medicaldevice', verbose_name='Медицинское изделие'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='workorderattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Тип содержимого'),
        ),
        migrations.AlterField(
            model_name='workorderattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='workorderattachment',
            name='file',
            field=models.FileField(upload_to='workorders/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='workorderattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AlterField(
            model_name='workorderattachment',
            name='workorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workorders.workorder', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='workordercomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='workordercomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='workordercomment',
            name='workorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workorders.workorder', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='workordertransitionlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='workordertransitionlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='workordertransitionlog',
            name='from_status',
            field=models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('on_hold', 'Ожидание'), ('resolved', 'Выполнена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], max_length=24, verbose_name='Из статуса'),
        ),
        migrations.AlterField(
            model_name='workordertransitionlog',
            name='to_status',
            field=models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('on_hold', 'Ожидание'), ('resolved', 'Выполнена'), ('closed', 'Закрыта'), ('cancelled', 'Отменена')], max_length=24, verbose_name='В статус'),
        ),
        migrations.AlterField(
            model_name='workordertransitionlog',
            name='workorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workorders.workorder', verbose_name='Заявка'),
        ),
    ]
