# Generated by Django 5.2.12 on 2026-05-20 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_organizational_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('active_directory', 'Active Directory')], default='active_directory', max_length=64)),
                ('subject_id', models.CharField(blank=True, help_text='AD SID/object identifier when available.', max_length=255)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('upn', models.CharField(blank=True, max_length=255)),
                ('distinguished_name', models.CharField(blank=True, max_length=500)),
                ('domain', models.CharField(blank=True, max_length=120)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('sync_status', models.CharField(choices=[('manual', 'Manual'), ('verified', 'Verified'), ('failed', 'Failed'), ('stale', 'Stale')], default='manual', max_length=32)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External identity',
                'verbose_name_plural': 'External identities',
                'ordering': ['provider', 'domain', 'username', 'id'],
                'indexes': [models.Index(fields=['provider', 'domain', 'username'], name='accounts_ex_provide_b59cd0_idx'), models.Index(fields=['provider', 'subject_id'], name='accounts_ex_provide_f789e1_idx'), models.Index(fields=['user', 'provider'], name='accounts_ex_user_id_d49f33_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('subject_id', ''), _negated=True), fields=('provider', 'subject_id'), name='accounts_external_identity_provider_subject_uniq'), models.UniqueConstraint(condition=models.Q(('username', ''), _negated=True), fields=('provider', 'domain', 'username'), name='accounts_external_identity_provider_domain_username_uniq'), models.UniqueConstraint(fields=('user', 'provider'), name='accounts_external_identity_user_provider_uniq')],
            },
        ),
    ]
