# Generated by Django 5.2.12 on 2026-05-28 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_externalidentity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalidentity',
            options={'ordering': ['provider', 'domain', 'username', 'id'], 'verbose_name': 'Внешняя учетная запись', 'verbose_name_plural': 'Внешние учетные записи'},
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Атрибуты'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='distinguished_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Distinguished name'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='domain',
            field=models.CharField(blank=True, max_length=120, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='Последняя ошибка'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='provider',
            field=models.CharField(choices=[('active_directory', 'Active Directory')], default='active_directory', max_length=64, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='subject_id',
            field=models.CharField(blank=True, help_text='AD SID или идентификатор объекта, если доступен.', max_length=255, verbose_name='Идентификатор субъекта'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='sync_status',
            field=models.CharField(choices=[('manual', 'Вручную'), ('verified', 'Проверено'), ('failed', 'Ошибка'), ('stale', 'Устарело')], default='manual', max_length=32, verbose_name='Статус синхронизации'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='upn',
            field=models.CharField(blank=True, max_length=255, verbose_name='UPN'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='externalidentity',
            name='username',
            field=models.CharField(blank=True, max_length=150, verbose_name='Логин'),
        ),
    ]
