# Generated by Django 5.2.12 on 2026-03-31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Не guessable UUID для внешних интеграций', unique=True, verbose_name='Внешний идентификатор')),
                ('patient_name', models.CharField(max_length=255, verbose_name='ФИО пациента')),
                ('patient_dob', models.CharField(help_text='ДД.ММ.ГГГГ', max_length=10, verbose_name='Дата рождения')),
                ('patient_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('service_id', models.CharField(choices=[('s1', 'КТ головного мозга'), ('s2', 'МРТ позвоночника'), ('s3', 'Рентген грудной клетки')], max_length=50, verbose_name='Услуга')),
                ('date_tag', models.DateField(blank=True, null=True, verbose_name='Целевая дата')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Крайняя дата')),
                ('priority_cito', models.BooleanField(default=False, verbose_name='CITO!')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('waiting', 'В очереди'), ('scheduled', 'Назначена'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='waiting', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запись листа ожидания',
                'verbose_name_plural': 'Записи листа ожидания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingListAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='waiting_list.waitinglistentry', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Журнал изменений',
                'verbose_name_plural': 'Журналы изменений',
                'ordering': ['-created_at'],
            },
        ),
    ]
