# Generated by Django 5.2.12 on 2026-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglistentry',
            name='priority_cito',
            field=models.BooleanField(db_index=True, default=False, verbose_name='CITO!'),
        ),
        migrations.AlterField(
            model_name='waitinglistentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'В очереди'), ('scheduled', 'Назначена'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], db_index=True, default='waiting', max_length=16, verbose_name='Статус'),
        ),
    ]
