# Generated by Django 5.2.12 on 2026-05-15 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0002_add_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglistentry',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waiting_list_entries', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='waitinglistentry',
            name='priority_cito',
            field=models.BooleanField(default=False, verbose_name='CITO!'),
        ),
        migrations.AlterField(
            model_name='waitinglistentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'В очереди'), ('scheduled', 'Назначена'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена')], default='waiting', max_length=16, verbose_name='Статус'),
        ),
    ]
