# Generated by Django 5.2.12 on 2026-05-15 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0003_waitinglistentry_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglistentry',
            name='patient_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddIndex(
            model_name='waitinglistauditlog',
            index=models.Index(fields=['action'], name='waiting_lis_action_3b931f_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistauditlog',
            index=models.Index(fields=['created_at'], name='waiting_lis_created_229ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['-created_at'], name='waiting_lis_created_ca5ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['status'], name='waiting_lis_status_2cd3ba_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['service_id'], name='waiting_lis_service_1383d6_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['priority_cito'], name='waiting_lis_priorit_b0daf1_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['date_tag'], name='waiting_lis_date_ta_4ec3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['date_end'], name='waiting_lis_date_en_3eff43_idx'),
        ),
        migrations.AddIndex(
            model_name='waitinglistentry',
            index=models.Index(fields=['patient_name'], name='waiting_lis_patient_34bfa6_idx'),
        ),
        migrations.AddConstraint(
            model_name='waitinglistentry',
            constraint=models.CheckConstraint(condition=models.Q(('date_tag__lte', models.F('date_end')), ('date_end__isnull', True), ('date_tag__isnull', True), _connector='OR'), name='waitinglist_date_range_consistent'),
        ),
    ]
