# Generated by Django 5.2.12 on 2026-05-28 22:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_list', '0004_alter_waitinglistentry_patient_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglistentry',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID, который нельзя угадать, для внешних интеграций', unique=True, verbose_name='Внешний идентификатор'),
        ),
    ]
