# Generated by Django 5.2.12 on 2026-05-20 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_id', models.CharField(max_length=160)),
                ('domain', models.CharField(max_length=64)),
                ('storage_kind', models.CharField(max_length=64)),
                ('action', models.CharField(choices=[('preview', 'Preview'), ('apply', 'Apply'), ('user_create', 'User create'), ('user_update', 'User update'), ('user_disable', 'User disable'), ('ad_link', 'AD link')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('before_hash', models.CharField(blank=True, max_length=80)),
                ('after_hash', models.CharField(blank=True, max_length=80)),
                ('masked_diff', models.JSONField(blank=True, default=dict)),
                ('validation_result', models.JSONField(blank=True, default=dict)),
                ('requires_restart', models.BooleanField(default=False)),
                ('requires_reindex', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='settings_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SettingsChangeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settings_change_comments', to=settings.AUTH_USER_MODEL)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='settings_center.settingschange')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SettingsEnvProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_label', models.CharField(max_length=120)),
                ('file_path', models.CharField(max_length=500)),
                ('masked_changes', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('exported', 'Exported'), ('applied_externally', 'Applied externally'), ('rejected', 'Rejected')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settings_env_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='settingschange',
            index=models.Index(fields=['setting_id', '-created_at'], name='settings_ce_setting_6ead31_idx'),
        ),
        migrations.AddIndex(
            model_name='settingschange',
            index=models.Index(fields=['domain', '-created_at'], name='settings_ce_domain_f88d45_idx'),
        ),
        migrations.AddIndex(
            model_name='settingschange',
            index=models.Index(fields=['status', '-created_at'], name='settings_ce_status_88b422_idx'),
        ),
        migrations.AddIndex(
            model_name='settingsenvproposal',
            index=models.Index(fields=['status', '-created_at'], name='settings_ce_status_9aec80_idx'),
        ),
    ]
