# Generated by Django 5.2.12 on 2026-05-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingschange',
            name='action',
            field=models.CharField(choices=[('preview', 'Предпросмотр'), ('apply', 'Применение'), ('user_create', 'Создание пользователя'), ('user_update', 'Обновление пользователя'), ('user_disable', 'Отключение пользователя'), ('ad_link', 'Связь с AD')], max_length=32),
        ),
        migrations.AlterField(
            model_name='settingschange',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('applied', 'Применено'), ('rejected', 'Отклонено'), ('failed', 'Ошибка')], default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='settingsenvproposal',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('exported', 'Экспортировано'), ('applied_externally', 'Применено вне портала'), ('rejected', 'Отклонено')], default='draft', max_length=32),
        ),
    ]
