# Generated by Django 5.2.12 on 2026-05-19 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_object_id', models.CharField(max_length=255)),
                ('content_hash', models.CharField(max_length=128)),
                ('schema_version', models.CharField(max_length=64)),
                ('extractor_version', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='ready', max_length=16)),
                ('extracted_at', models.DateTimeField()),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('raw_path', models.CharField(max_length=500)),
                ('safe_path', models.CharField(blank=True, max_length=500)),
                ('pii_policy_applied', models.CharField(blank=True, max_length=120)),
                ('scope_tokens', models.JSONField(blank=True, default=list)),
                ('sensitivity', models.CharField(max_length=32)),
                ('blocked_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Memory snapshot',
                'verbose_name_plural': 'Memory snapshots',
                'ordering': ['-extracted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryEvalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('suite', models.CharField(default='smoke', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('question', models.TextField()),
                ('expected_source_codes', models.JSONField(blank=True, default=list)),
                ('expected_chunk_ids', models.JSONField(blank=True, default=list)),
                ('forbidden_source_codes', models.JSONField(blank=True, default=list)),
                ('forbidden_scope_tokens', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Memory eval case',
                'verbose_name_plural': 'Memory eval cases',
                'ordering': ['suite', 'code'],
                'indexes': [models.Index(fields=['suite'], name='memory_memo_suite_4304aa_idx'), models.Index(fields=['status'], name='memory_memo_status_41e598_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.CharField(max_length=160, unique=True)),
                ('source_code', models.CharField(max_length=120)),
                ('source_object_id', models.CharField(max_length=255)),
                ('snapshot_hash', models.CharField(max_length=128)),
                ('position', models.PositiveIntegerField(default=0)),
                ('text_path', models.CharField(blank=True, max_length=500)),
                ('text_hash', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scope_tokens', models.JSONField(blank=True, default=list)),
                ('sensitivity', models.CharField(max_length=32)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chunks', to='memory.memorysnapshot')),
            ],
            options={
                'verbose_name': 'Memory chunk',
                'verbose_name_plural': 'Memory chunks',
                'ordering': ['snapshot_id', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemorySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('source_kind', models.CharField(max_length=64)),
                ('domain', models.CharField(max_length=64)),
                ('owner', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('error', 'Error')], default='enabled', max_length=16)),
                ('sync_mode', models.CharField(blank=True, max_length=32)),
                ('scope_rule', models.CharField(blank=True, max_length=120)),
                ('sensitivity', models.CharField(max_length=32)),
                ('pii_policy', models.CharField(blank=True, max_length=120)),
                ('extractor_profile', models.CharField(blank=True, max_length=120)),
                ('chunking_profile', models.CharField(blank=True, max_length=120)),
                ('index_profiles', models.JSONField(blank=True, default=list)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('watermarks', models.JSONField(blank=True, default=dict)),
                ('last_discovered_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Memory source',
                'verbose_name_plural': 'Memory sources',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['status'], name='memory_memo_status_cc6153_idx'), models.Index(fields=['domain'], name='memory_memo_domain_805040_idx'), models.Index(fields=['source_kind'], name='memory_memo_source__4e1f77_idx'), models.Index(fields=['sensitivity'], name='memory_memo_sensiti_3cdff7_idx')],
            },
        ),
        migrations.AddField(
            model_name='memorysnapshot',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='memory.memorysource'),
        ),
        migrations.CreateModel(
            name='MemoryIndexJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_kind', models.CharField(choices=[('discover', 'Discover'), ('sync', 'Sync'), ('reindex', 'Reindex'), ('eval', 'Eval')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_index_jobs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='index_jobs', to='memory.memorysource')),
            ],
            options={
                'verbose_name': 'Memory index job',
                'verbose_name_plural': 'Memory index jobs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryAccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=120)),
                ('query_hash', models.CharField(blank=True, max_length=128)),
                ('tool_name', models.CharField(default='memory.search', max_length=120)),
                ('allowed_scope_tokens', models.JSONField(blank=True, default=list)),
                ('returned_chunk_ids', models.JSONField(blank=True, default=list)),
                ('returned_fact_ids', models.JSONField(blank=True, default=list)),
                ('denied_reason', models.TextField(blank=True)),
                ('policy_decision', models.CharField(max_length=32)),
                ('retrieval_trace', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_access_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory access audit',
                'verbose_name_plural': 'Memory access audits',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='memory_memo_actor_i_5aadc3_idx'), models.Index(fields=['request_id'], name='memory_memo_request_5b4f86_idx'), models.Index(fields=['policy_decision'], name='memory_memo_policy__f4821c_idx'), models.Index(fields=['tool_name'], name='memory_memo_tool_na_b880d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryGraphFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_id', models.CharField(max_length=160, unique=True)),
                ('snapshot_hash', models.CharField(max_length=128)),
                ('subject_id', models.CharField(max_length=160)),
                ('predicate', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=160)),
                ('subject_type', models.CharField(blank=True, max_length=80)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('extracted_by', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scope_tokens', models.JSONField(blank=True, default=list)),
                ('sensitivity', models.CharField(max_length=32)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graph_facts', to='memory.memorychunk')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graph_facts', to='memory.memorysnapshot')),
            ],
            options={
                'verbose_name': 'Memory graph fact',
                'verbose_name_plural': 'Memory graph facts',
                'ordering': ['fact_id'],
                'indexes': [models.Index(fields=['subject_id'], name='memory_memo_subject_93247f_idx'), models.Index(fields=['predicate'], name='memory_memo_predica_a15b89_idx'), models.Index(fields=['object_id'], name='memory_memo_object__ff628f_idx'), models.Index(fields=['snapshot_hash'], name='memory_memo_snapsho_bd7b0c_idx'), models.Index(fields=['is_active'], name='memory_memo_is_acti_56c93d_idx'), models.Index(fields=['sensitivity'], name='memory_memo_sensiti_7f06ef_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='memory_graph_fact_confidence_0_1'), models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_from__lte', models.F('valid_to')), _connector='OR'), name='memory_graph_fact_valid_range')],
            },
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['source_code', 'source_object_id'], name='memory_memo_source__2db100_idx'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['snapshot_hash'], name='memory_memo_snapsho_c12ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['text_hash'], name='memory_memo_text_ha_750a7a_idx'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['is_active'], name='memory_memo_is_acti_fc6cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='memorychunk',
            index=models.Index(fields=['sensitivity'], name='memory_memo_sensiti_b16bb8_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorychunk',
            constraint=models.UniqueConstraint(fields=('snapshot', 'position'), name='memory_chunk_snapshot_position_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorychunk',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_from__lte', models.F('valid_to')), _connector='OR'), name='memory_chunk_valid_range'),
        ),
        migrations.AddIndex(
            model_name='memorysnapshot',
            index=models.Index(fields=['source', 'source_object_id'], name='memory_memo_source__618304_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysnapshot',
            index=models.Index(fields=['content_hash'], name='memory_memo_content_9a6886_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysnapshot',
            index=models.Index(fields=['status'], name='memory_memo_status_7a8c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysnapshot',
            index=models.Index(fields=['is_active'], name='memory_memo_is_acti_2e1339_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysnapshot',
            index=models.Index(fields=['sensitivity'], name='memory_memo_sensiti_482823_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysnapshot',
            index=models.Index(fields=['-extracted_at', '-id'], name='memory_memo_extract_61ed55_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorysnapshot',
            constraint=models.UniqueConstraint(fields=('source', 'source_object_id', 'content_hash'), name='memory_snapshot_source_obj_hash_uniq'),
        ),
        migrations.AddConstraint(
            model_name='memorysnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('source', 'source_object_id'), name='memory_one_active_snapshot_per_obj'),
        ),
        migrations.AddConstraint(
            model_name='memorysnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_from__lte', models.F('valid_to')), _connector='OR'), name='memory_snapshot_valid_range'),
        ),
        migrations.AddIndex(
            model_name='memoryindexjob',
            index=models.Index(fields=['job_kind'], name='memory_memo_job_kin_f2d44a_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryindexjob',
            index=models.Index(fields=['status'], name='memory_memo_status_7c7df9_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryindexjob',
            index=models.Index(fields=['request_id'], name='memory_memo_request_dc028e_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryindexjob',
            index=models.Index(fields=['-created_at', '-id'], name='memory_memo_created_382a34_idx'),
        ),
        migrations.AddConstraint(
            model_name='memoryindexjob',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('started_at__isnull', True), ('started_at__lte', models.F('finished_at')), _connector='OR'), name='memory_index_job_time_range'),
        ),
        migrations.AddConstraint(
            model_name='memoryindexjob',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='memory_index_job_attempts_lte_max'),
        ),
    ]
