# Generated by Django 5.2.12 on 2026-05-20 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryGraphEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(max_length=160, unique=True)),
                ('entity_type', models.CharField(max_length=80)),
                ('canonical_name', models.CharField(max_length=255)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('scope_tokens', models.JSONField(blank=True, default=list)),
                ('sensitivity', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Memory graph entity',
                'verbose_name_plural': 'Memory graph entities',
                'ordering': ['entity_type', 'canonical_name'],
                'indexes': [models.Index(fields=['entity_type'], name='memory_memo_entity__fd009f_idx'), models.Index(fields=['canonical_name'], name='memory_memo_canonic_3e9e89_idx'), models.Index(fields=['sensitivity'], name='memory_memo_sensiti_5c3f3b_idx'), models.Index(fields=['is_active'], name='memory_memo_is_acti_97dd39_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryIngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_ingestion_runs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_runs', to='memory.memorysource')),
            ],
            options={
                'verbose_name': 'Memory ingestion run',
                'verbose_name_plural': 'Memory ingestion runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemorySourceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('object_uri', models.CharField(max_length=1000)),
                ('relative_path', models.CharField(max_length=1000)),
                ('file_name', models.CharField(max_length=255)),
                ('extension', models.CharField(blank=True, max_length=32)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('mtime', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=128)),
                ('etag_or_inode', models.CharField(blank=True, max_length=255)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_stable_at', models.DateTimeField(blank=True, null=True)),
                ('discovery_status', models.CharField(choices=[('seen', 'Seen'), ('missing', 'Missing'), ('changed', 'Changed'), ('error', 'Error')], default='seen', max_length=16)),
                ('ingestion_status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('ingested', 'Ingested'), ('partial', 'Partial'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('partial_reason', models.TextField(blank=True)),
                ('acl_fingerprint', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_objects', to='memory.memorysource')),
            ],
            options={
                'verbose_name': 'Memory source object',
                'verbose_name_plural': 'Memory source objects',
                'ordering': ['source__code', 'relative_path'],
            },
        ),
        migrations.CreateModel(
            name='MemoryIngestionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_kind', models.CharField(choices=[('encrypted_file', 'Encrypted file'), ('unsupported_format', 'Unsupported format'), ('file_too_large', 'File too large'), ('partial_indexed', 'Partial indexed'), ('parser_timeout', 'Parser timeout'), ('ocr_timeout', 'OCR timeout'), ('pii_blocked', 'PII blocked'), ('secret_blocked', 'Secret blocked'), ('acl_unresolved', 'ACL unresolved'), ('schema_unknown_type', 'Schema unknown type'), ('schema_unknown_relation', 'Schema unknown relation'), ('canonicalization_conflict', 'Canonicalization conflict')], max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('needs_expert_review', 'Needs expert review'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=32)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('blocker', 'Blocker')], default='warning', max_length=16)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_issues', to='memory.memorysource')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='memory.memoryingestionrun')),
                ('source_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingestion_issues', to='memory.memorysourceobject')),
            ],
            options={
                'verbose_name': 'Memory ingestion issue',
                'verbose_name_plural': 'Memory ingestion issues',
                'ordering': ['status', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryGraphExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graph_extraction_runs', to='memory.memorysnapshot')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='graph_extraction_runs', to='memory.memorysource')),
            ],
            options={
                'verbose_name': 'Memory graph extraction run',
                'verbose_name_plural': 'Memory graph extraction runs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['source', '-created_at'], name='memory_memo_source__7da429_idx'), models.Index(fields=['snapshot'], name='memory_memo_snapsho_76b3e8_idx'), models.Index(fields=['status'], name='memory_memo_status_926b76_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('started_at__isnull', True), ('started_at__lte', models.F('finished_at')), _connector='OR'), name='memory_graph_extraction_run_time_range')],
            },
        ),
        migrations.CreateModel(
            name='MemoryGraphReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_kind', models.CharField(choices=[('unknown_type', 'Unknown type'), ('unknown_relation', 'Unknown relation'), ('low_confidence', 'Low confidence'), ('canonicalization_conflict', 'Canonicalization conflict'), ('dlp_warning', 'DLP warning')], max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('needs_expert_review', 'Needs expert review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('decision', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_graph_review_items', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graph_review_items', to='memory.memorysnapshot')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graph_review_items', to='memory.memorysource')),
            ],
            options={
                'verbose_name': 'Memory graph review item',
                'verbose_name_plural': 'Memory graph review items',
                'ordering': ['status', '-created_at', '-id'],
                'indexes': [models.Index(fields=['item_kind'], name='memory_memo_item_ki_036151_idx'), models.Index(fields=['status'], name='memory_memo_status_2e3ec6_idx'), models.Index(fields=['source', 'status'], name='memory_memo_source__b047b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryGraphSchemaProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_kind', models.CharField(choices=[('entity_type', 'Entity type'), ('relation_type', 'Relation type'), ('attribute_type', 'Attribute type'), ('canonicalization_rule', 'Canonicalization rule'), ('forbidden_pattern', 'Forbidden pattern')], max_length=64)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('needs_expert_review', 'Needs expert review'), ('expert_approved', 'Expert approved'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='proposed', max_length=32)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('rationale', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_graph_schema_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory graph schema proposal',
                'verbose_name_plural': 'Memory graph schema proposals',
                'ordering': ['status', '-created_at', '-id'],
                'indexes': [models.Index(fields=['proposal_kind'], name='memory_memo_proposa_51065d_idx'), models.Index(fields=['status'], name='memory_memo_status_1d0681_idx'), models.Index(fields=['department'], name='memory_memo_departm_44bd24_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='memory_graph_schema_proposal_confidence_0_1')],
            },
        ),
        migrations.AddIndex(
            model_name='memoryingestionrun',
            index=models.Index(fields=['source', '-created_at'], name='memory_memo_source__87ddcc_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryingestionrun',
            index=models.Index(fields=['status'], name='memory_memo_status_085179_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryingestionrun',
            index=models.Index(fields=['dry_run'], name='memory_memo_dry_run_4c263e_idx'),
        ),
        migrations.AddConstraint(
            model_name='memoryingestionrun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('started_at__isnull', True), ('started_at__lte', models.F('finished_at')), _connector='OR'), name='memory_ingestion_run_time_range'),
        ),
        migrations.AddIndex(
            model_name='memorysourceobject',
            index=models.Index(fields=['source', 'object_id'], name='memory_memo_source__a004ea_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysourceobject',
            index=models.Index(fields=['source', 'relative_path'], name='memory_memo_source__619d63_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysourceobject',
            index=models.Index(fields=['content_hash'], name='memory_memo_content_a64aab_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysourceobject',
            index=models.Index(fields=['discovery_status'], name='memory_memo_discove_f5b808_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysourceobject',
            index=models.Index(fields=['ingestion_status'], name='memory_memo_ingesti_f9b770_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysourceobject',
            index=models.Index(fields=['last_seen_at'], name='memory_memo_last_se_82d493_idx'),
        ),
        migrations.AddConstraint(
            model_name='memorysourceobject',
            constraint=models.UniqueConstraint(fields=('source', 'object_id'), name='memory_source_object_source_object_uniq'),
        ),
        migrations.AddIndex(
            model_name='memoryingestionissue',
            index=models.Index(fields=['source', 'status'], name='memory_memo_source__660180_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryingestionissue',
            index=models.Index(fields=['issue_kind'], name='memory_memo_issue_k_db143b_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryingestionissue',
            index=models.Index(fields=['severity'], name='memory_memo_severit_43421c_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryingestionissue',
            index=models.Index(fields=['created_at'], name='memory_memo_created_cc167a_idx'),
        ),
    ]
