# Generated by Django 5.2.12 on 2026-05-20 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_pendingaction_expires_at'),
        ('memory', '0002_memorygraphentity_memoryingestionrun_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryindexjob',
            name='job_kind',
            field=models.CharField(choices=[('discover', 'Discover'), ('sync', 'Sync'), ('reindex', 'Reindex'), ('eval', 'Eval'), ('remember', 'Remember'), ('reflect', 'Reflect')], max_length=16),
        ),
        migrations.CreateModel(
            name='MemoryKnowledgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_id', models.CharField(max_length=160, unique=True)),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization')], max_length=32)),
                ('kind', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('procedure', 'Procedure'), ('decision', 'Decision'), ('secret_reference', 'Secret reference')], default='fact', max_length=32)),
                ('text', models.TextField()),
                ('text_hash', models.CharField(max_length=128)),
                ('sensitivity', models.CharField(default='internal', max_length=32)),
                ('scope_tokens', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted'), ('superseded', 'Superseded'), ('quarantined', 'Quarantined')], default='active', max_length=32)),
                ('source_message_ids', models.JSONField(blank=True, default=list)),
                ('source_content_hash', models.CharField(blank=True, max_length=128)),
                ('provenance', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_memory_knowledge_items', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_knowledge_items', to=settings.AUTH_USER_MODEL)),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_knowledge_items', to='ai.chatsession')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='memory.memoryknowledgeitem')),
            ],
            options={
                'verbose_name': 'Memory knowledge item',
                'verbose_name_plural': 'Memory knowledge items',
                'ordering': ['scope', 'owner_user_id', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryKnowledgeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(choices=[('remembered', 'Remembered'), ('edited', 'Edited'), ('deleted', 'Deleted'), ('reflected', 'Reflected'), ('promoted', 'Promoted'), ('rejected', 'Rejected'), ('secret_captured', 'Secret captured')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_knowledge_events', to=settings.AUTH_USER_MODEL)),
                ('knowledge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='memory.memoryknowledgeitem')),
            ],
            options={
                'verbose_name': 'Memory knowledge event',
                'verbose_name_plural': 'Memory knowledge events',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryKnowledgeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_text', models.TextField()),
                ('proposed_payload', models.JSONField(blank=True, default=dict)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('needs_review', 'Needs review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('merged', 'Merged'), ('superseded', 'Superseded')], default='proposed', max_length=32)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_candidates', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_candidate_reviews', to=settings.AUTH_USER_MODEL)),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_candidates', to='memory.memoryknowledgeitem')),
            ],
            options={
                'verbose_name': 'Memory knowledge candidate',
                'verbose_name_plural': 'Memory knowledge candidates',
                'ordering': ['status', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryReflectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_reflection_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Memory reflection run',
                'verbose_name_plural': 'Memory reflection runs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MemoryWriteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message_ids', models.JSONField(blank=True, default=list)),
                ('target_scope', models.CharField(choices=[('personal', 'Personal'), ('organization', 'Organization')], default='personal', max_length=32)),
                ('user_note', models.TextField(blank=True)),
                ('importance', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('accepted', 'Accepted'), ('candidate_created', 'Candidate created'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_write_requests', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_write_requests', to='ai.chatsession')),
            ],
            options={
                'verbose_name': 'Memory write request',
                'verbose_name_plural': 'Memory write requests',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecretHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=160, unique=True)),
                ('provider', models.CharField(choices=[('external_vault_link', 'External vault link'), ('disabled', 'Disabled'), ('local_stub', 'Local stub'), ('openbao', 'OpenBao')], default='external_vault_link', max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('scope', models.CharField(blank=True, max_length=32)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('unavailable', 'Unavailable')], default='active', max_length=32)),
                ('sensitivity', models.CharField(default='secret', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_secret_handles', to=settings.AUTH_USER_MODEL)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secret_handles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Secret handle',
                'verbose_name_plural': 'Secret handles',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SecretAccessAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('link', 'Link'), ('rotate', 'Rotate'), ('revoke', 'Revoke'), ('service_resolve', 'Service resolve')], max_length=32)),
                ('decision', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied'), ('failed', 'Failed')], max_length=32)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secret_access_audits', to=settings.AUTH_USER_MODEL)),
                ('secret_handle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_audits', to='memory.secrethandle')),
            ],
            options={
                'verbose_name': 'Secret access audit',
                'verbose_name_plural': 'Secret access audits',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='memoryknowledgeitem',
            index=models.Index(fields=['scope', 'status'], name='memory_memo_scope_1bac77_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgeitem',
            index=models.Index(fields=['owner_user', 'status'], name='memory_memo_owner_u_6faa57_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgeitem',
            index=models.Index(fields=['text_hash'], name='memory_memo_text_ha_9d066e_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgeitem',
            index=models.Index(fields=['sensitivity'], name='memory_memo_sensiti_0fd56e_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgeitem',
            index=models.Index(fields=['memory_id'], name='memory_memo_memory__717b7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='memoryknowledgeitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('owner_user__isnull', False), ('scope', 'personal')), ('scope', 'organization'), _connector='OR'), name='memory_knowledge_personal_has_owner'),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgeevent',
            index=models.Index(fields=['event_type'], name='memory_memo_event_t_f5989d_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgeevent',
            index=models.Index(fields=['actor', 'created_at'], name='memory_memo_actor_i_10b202_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgecandidate',
            index=models.Index(fields=['status'], name='memory_memo_status_8c8328_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgecandidate',
            index=models.Index(fields=['created_by', '-created_at'], name='memory_memo_created_04a156_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgecandidate',
            index=models.Index(fields=['reviewer', 'reviewed_at'], name='memory_memo_reviewe_a73484_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryreflectionrun',
            index=models.Index(fields=['status'], name='memory_memo_status_30fa4d_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryreflectionrun',
            index=models.Index(fields=['dry_run'], name='memory_memo_dry_run_4891ee_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryreflectionrun',
            index=models.Index(fields=['window_start', 'window_end'], name='memory_memo_window__8a4480_idx'),
        ),
        migrations.AddConstraint(
            model_name='memoryreflectionrun',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('started_at__isnull', True), ('started_at__lte', models.F('finished_at')), _connector='OR'), name='memory_reflection_run_time_range'),
        ),
        migrations.AddIndex(
            model_name='memorywriterequest',
            index=models.Index(fields=['actor', '-created_at'], name='memory_memo_actor_i_6b8482_idx'),
        ),
        migrations.AddIndex(
            model_name='memorywriterequest',
            index=models.Index(fields=['target_scope', 'status'], name='memory_memo_target__8b5521_idx'),
        ),
        migrations.AddIndex(
            model_name='memorywriterequest',
            index=models.Index(fields=['status'], name='memory_memo_status_5fa52b_idx'),
        ),
        migrations.AddIndex(
            model_name='memorywriterequest',
            index=models.Index(fields=['request_id'], name='memory_memo_request_fa5135_idx'),
        ),
        migrations.AddIndex(
            model_name='secrethandle',
            index=models.Index(fields=['provider', 'status'], name='memory_secr_provide_0f37d9_idx'),
        ),
        migrations.AddIndex(
            model_name='secrethandle',
            index=models.Index(fields=['owner_user', 'status'], name='memory_secr_owner_u_648525_idx'),
        ),
        migrations.AddIndex(
            model_name='secrethandle',
            index=models.Index(fields=['handle'], name='memory_secr_handle_734cf6_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaccessaudit',
            index=models.Index(fields=['actor', '-created_at'], name='memory_secr_actor_i_b42d52_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaccessaudit',
            index=models.Index(fields=['secret_handle', '-created_at'], name='memory_secr_secret__dbf52f_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaccessaudit',
            index=models.Index(fields=['action', 'decision'], name='memory_secr_action_332b03_idx'),
        ),
        migrations.AddIndex(
            model_name='secretaccessaudit',
            index=models.Index(fields=['request_id'], name='memory_secr_request_6e110c_idx'),
        ),
    ]
