# Generated by Django 5.2.12 on 2026-05-21 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_alter_memoryindexjob_job_kind_memoryknowledgeitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=160, unique=True)),
                ('claim_type', models.CharField(choices=[('fact', 'Fact'), ('preference', 'Preference'), ('procedure', 'Procedure'), ('policy', 'Policy'), ('decision', 'Decision'), ('metric_observation', 'Metric observation'), ('incident', 'Incident'), ('action_outcome', 'Action outcome')], default='fact', max_length=32)),
                ('text', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('contested', 'Contested'), ('superseded', 'Superseded'), ('expired', 'Expired')], default='candidate', max_length=32)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('evidence_hash', models.CharField(blank=True, max_length=128)),
                ('scope_tokens', models.JSONField(blank=True, default=list)),
                ('sensitivity', models.CharField(default='internal', max_length=32)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Memory claim',
                'verbose_name_plural': 'Memory claims',
                'ordering': ['status', '-observed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='memorysource',
            name='authority_class',
            field=models.CharField(blank=True, choices=[('system_of_record', 'System of record'), ('approved_corpus', 'Approved corpus'), ('approved_user_memory', 'Approved user memory'), ('reviewed_org_knowledge', 'Reviewed organization knowledge'), ('external_observation', 'External observation'), ('candidate_input', 'Candidate input')], max_length=64),
        ),
        migrations.AddField(
            model_name='memorysource',
            name='requires_source_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memorysource',
            name='review_owner',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='memorysource',
            name='trust_status',
            field=models.CharField(blank=True, choices=[('trusted', 'Trusted'), ('review_required', 'Review required'), ('candidate_only', 'Candidate only'), ('quarantined', 'Quarantined'), ('blocked', 'Blocked')], max_length=32),
        ),
        migrations.AddField(
            model_name='memorysource',
            name='trusted_context_kinds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='memorysource',
            name='trusted_for_context',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorysource',
            name='untrusted_handling',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='memorysource',
            index=models.Index(fields=['trust_status', 'trusted_for_context'], name='memory_memo_trust_s_b8333d_idx'),
        ),
        migrations.AddIndex(
            model_name='memorysource',
            index=models.Index(fields=['authority_class'], name='memory_memo_authori_e26fd9_idx'),
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='knowledge_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='memory.memoryknowledgeitem'),
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_claim_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='memory.memorysnapshot'),
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='memory.memorysource'),
        ),
        migrations.AddField(
            model_name='memoryclaim',
            name='source_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='memory.memorychunk'),
        ),
        migrations.AddIndex(
            model_name='memoryclaim',
            index=models.Index(fields=['claim_id'], name='memory_memo_claim_i_d3231a_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryclaim',
            index=models.Index(fields=['claim_type', 'status'], name='memory_memo_claim_t_f7ca03_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryclaim',
            index=models.Index(fields=['status', 'sensitivity'], name='memory_memo_status_820504_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryclaim',
            index=models.Index(fields=['source', 'status'], name='memory_memo_source__91eb09_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryclaim',
            index=models.Index(fields=['knowledge_item', 'status'], name='memory_memo_knowled_a610fe_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryclaim',
            index=models.Index(fields=['reviewer', 'reviewed_at'], name='memory_memo_reviewe_13182f_idx'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaim',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='memory_claim_confidence_0_1'),
        ),
        migrations.AddConstraint(
            model_name='memoryclaim',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_from__isnull', True), ('valid_from__lte', models.F('valid_to')), _connector='OR'), name='memory_claim_valid_range'),
        ),
    ]
