# Generated by Django 5.2.12 on 2026-05-22 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_alter_agentactionlog_actor_alter_chatsession_user_and_more'),
        ('memory', '0004_memorybelief_memoryclaim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryknowledgeitem',
            name='index_status',
            field=models.CharField(default='indexing_pending', max_length=32),
        ),
        migrations.AddField(
            model_name='memoryknowledgeitem',
            name='knowledge_file_commit',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='memoryknowledgeitem',
            name='knowledge_file_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='memoryknowledgeitem',
            name='knowledge_file_path',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='memoryknowledgeitem',
            name='source_code',
            field=models.CharField(default='chat', max_length=120),
        ),
        migrations.AddField(
            model_name='memoryknowledgeitem',
            name='source_kind',
            field=models.CharField(default='chat', max_length=64),
        ),
        migrations.AddField(
            model_name='memoryknowledgeitem',
            name='source_refs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='memoryaccessaudit',
            name='actor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='memory_access_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryclaim',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='memory_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryclaim',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_claim_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorygraphreviewitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_graph_review_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorygraphschemaproposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_graph_schema_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryindexjob',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_index_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryingestionrun',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_ingestion_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgecandidate',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='memory_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgecandidate',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_candidate_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeevent',
            name='actor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='memory_knowledge_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeitem',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='created_memory_knowledge_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeitem',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_knowledge_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeitem',
            name='source_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_knowledge_items', to='ai.chatsession'),
        ),
        migrations.AlterField(
            model_name='memoryreflectionrun',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_reflection_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorywriterequest',
            name='actor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='memory_write_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorywriterequest',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_write_requests', to='ai.chatsession'),
        ),
        migrations.AlterField(
            model_name='secretaccessaudit',
            name='actor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='secret_access_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secrethandle',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='created_secret_handles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secrethandle',
            name='owner_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secret_handles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgeitem',
            index=models.Index(fields=['source_code', 'source_kind'], name='memory_memo_source__9643a9_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryknowledgeitem',
            index=models.Index(fields=['index_status'], name='memory_memo_index_s_d5b3e2_idx'),
        ),
    ]
