# Generated by Django 5.2.12 on 2026-05-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_memoryknowledgeitem_index_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=180, unique=True)),
                ('corpus_type', models.CharField(choices=[('knowledge', 'Knowledge'), ('source_data', 'Source data')], max_length=32)),
                ('object_kind', models.CharField(choices=[('knowledge_item', 'Knowledge item'), ('source_object', 'Source object'), ('summary', 'Summary'), ('analytics_slice', 'Analytics slice')], max_length=64)),
                ('source_code', models.CharField(max_length=120)),
                ('source_kind', models.CharField(max_length=64)),
                ('source_object_ref', models.CharField(blank=True, max_length=255)),
                ('source_uri', models.CharField(blank=True, max_length=1000)),
                ('source_refs', models.JSONField(blank=True, default=list)),
                ('body_hash', models.CharField(blank=True, max_length=128)),
                ('scope_tokens', models.JSONField(blank=True, default=list)),
                ('sensitivity', models.CharField(max_length=32)),
                ('index_status', models.CharField(choices=[('indexing_pending', 'Indexing pending'), ('ready', 'Ready'), ('deleted', 'Deleted'), ('failed', 'Failed')], default='indexing_pending', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('knowledge_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_documents', to='memory.memoryknowledgeitem')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_documents', to='memory.memorysource')),
                ('source_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_documents', to='memory.memorysourceobject')),
            ],
            options={
                'verbose_name': 'Memory search document',
                'verbose_name_plural': 'Memory search documents',
                'ordering': ['corpus_type', 'source_code', 'document_id'],
                'indexes': [models.Index(fields=['document_id'], name='memory_memo_documen_35df2f_idx'), models.Index(fields=['corpus_type', 'object_kind'], name='memory_memo_corpus__27b585_idx'), models.Index(fields=['source_code', 'source_kind'], name='memory_memo_source__2fb521_idx'), models.Index(fields=['source_object_ref'], name='memory_memo_source__ecde31_idx'), models.Index(fields=['index_status'], name='memory_memo_index_s_cdc77f_idx'), models.Index(fields=['sensitivity'], name='memory_memo_sensiti_597a92_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('corpus_type', 'knowledge'), ('knowledge_item__isnull', False)), models.Q(('corpus_type', 'source_data'), ('source_object__isnull', False)), ('object_kind__in', ['summary', 'analytics_slice']), _connector='OR'), name='memory_search_document_target_present')],
            },
        ),
    ]
