# Generated by Django 5.2.12 on 2026-05-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_memorysearchdocument'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='memorygraphextractionrun',
            name='memory_memo_snapsho_76b3e8_idx',
        ),
        migrations.RemoveField(
            model_name='memoryclaim',
            name='source_chunk',
        ),
        migrations.RemoveField(
            model_name='memorygraphreviewitem',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='memorygraphextractionrun',
            name='snapshot',
        ),
        migrations.RemoveField(
            model_name='memoryclaim',
            name='snapshot',
        ),
        migrations.DeleteModel(
            name='MemoryGraphFact',
        ),
        migrations.DeleteModel(
            name='MemoryChunk',
        ),
        migrations.DeleteModel(
            name='MemorySnapshot',
        ),
    ]
