# Generated by Django 5.2.12 on 2026-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0007_remove_memorychunk_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memorysearchdocument',
            options={'ordering': ['corpus_type', 'document_id'], 'verbose_name': 'Memory search document', 'verbose_name_plural': 'Memory search documents'},
        ),
        migrations.RemoveIndex(
            model_name='memorysearchdocument',
            name='memory_memo_source__2fb521_idx',
        ),
        migrations.RemoveIndex(
            model_name='memorysearchdocument',
            name='memory_memo_source__ecde31_idx',
        ),
        migrations.RemoveIndex(
            model_name='memorysearchdocument',
            name='memory_memo_sensiti_597a92_idx',
        ),
        migrations.RemoveField(
            model_name='memoryaccessaudit',
            name='returned_chunk_ids',
        ),
        migrations.RemoveField(
            model_name='memoryevalcase',
            name='expected_chunk_ids',
        ),
        migrations.RemoveField(
            model_name='memoryknowledgeitem',
            name='text',
        ),
        migrations.RemoveField(
            model_name='memorysearchdocument',
            name='scope_tokens',
        ),
        migrations.RemoveField(
            model_name='memorysearchdocument',
            name='sensitivity',
        ),
        migrations.RemoveField(
            model_name='memorysearchdocument',
            name='source',
        ),
        migrations.RemoveField(
            model_name='memorysearchdocument',
            name='source_code',
        ),
        migrations.RemoveField(
            model_name='memorysearchdocument',
            name='source_kind',
        ),
        migrations.RemoveField(
            model_name='memorysearchdocument',
            name='source_object_ref',
        ),
        migrations.RemoveField(
            model_name='memorysearchdocument',
            name='source_refs',
        ),
        migrations.RemoveField(
            model_name='memorysearchdocument',
            name='source_uri',
        ),
        migrations.AddField(
            model_name='memoryaccessaudit',
            name='returned_document_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='memoryevalcase',
            name='expected_document_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='MemoryClaim',
        ),
    ]
