# Generated by Django 5.2.12 on 2026-05-27 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0009_alter_memoryingestionissue_issue_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('acknowledge', 'Acknowledge'), ('assign', 'Assign'), ('request_expert_review', 'Request expert review'), ('resolve', 'Resolve'), ('ignore', 'Ignore'), ('reopen', 'Reopen'), ('comment', 'Comment'), ('dry_run_reindex', 'Dry-run reindex'), ('enqueue_reindex', 'Enqueue reindex'), ('retry_index', 'Retry index'), ('delete_stale_index', 'Delete stale index'), ('mark_index_cleaned', 'Mark index cleaned'), ('create_issue', 'Create issue')], max_length=40)),
                ('decision', models.CharField(choices=[('applied', 'Applied'), ('queued', 'Queued'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('info', 'Info')], default='applied', max_length=32)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Memory review action',
                'verbose_name_plural': 'Memory review actions',
                'ordering': ['-created_at', '-id'],
                'permissions': [('view_review_queue', 'Can view memory review queue'), ('review_issues', 'Can review memory issues'), ('review_privacy_issues', 'Can review memory privacy issues'), ('manage_search_index', 'Can manage memory search index'), ('view_memory_access_audit', 'Can view memory access audit')],
            },
        ),
        migrations.AddField(
            model_name='memoryingestionissue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_memory_ingestion_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoryingestionissue',
            name='resolution_code',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='memoryingestionissue',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='memoryingestionissue',
            name='review_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryingestionissue',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_memory_ingestion_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryingestionissue',
            name='issue_kind',
            field=models.CharField(choices=[('encrypted_file', 'Encrypted file'), ('unsupported_format', 'Unsupported format'), ('file_too_large', 'File too large'), ('partial_indexed', 'Partial indexed'), ('parser_timeout', 'Parser timeout'), ('ocr_timeout', 'OCR timeout'), ('pii_blocked', 'PII blocked'), ('pii_audit', 'PII audit'), ('secret_blocked', 'Secret blocked'), ('acl_unresolved', 'ACL unresolved'), ('schema_unknown_type', 'Schema unknown type'), ('schema_unknown_relation', 'Schema unknown relation'), ('canonicalization_conflict', 'Canonicalization conflict'), ('index_failed', 'Index failed'), ('index_stale', 'Index stale'), ('fts_missing', 'FTS missing'), ('vector_missing', 'Vector missing'), ('source_deleted_index_left', 'Source deleted index left')], max_length=64),
        ),
        migrations.AddIndex(
            model_name='memoryingestionissue',
            index=models.Index(fields=['assigned_to', 'status'], name='memory_memo_assigne_5353ac_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryingestionissue',
            index=models.Index(fields=['review_due_at'], name='memory_memo_review__84dded_idx'),
        ),
        migrations.AddField(
            model_name='memoryreviewaction',
            name='access_audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='memory.memoryaccessaudit'),
        ),
        migrations.AddField(
            model_name='memoryreviewaction',
            name='actor',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='memory_review_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memoryreviewaction',
            name='index_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='memory.memoryindexjob'),
        ),
        migrations.AddField(
            model_name='memoryreviewaction',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='memory.memoryingestionissue'),
        ),
        migrations.AddField(
            model_name='memoryreviewaction',
            name='search_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='memory.memorysearchdocument'),
        ),
        migrations.AddField(
            model_name='memoryreviewaction',
            name='source_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='memory.memorysourceobject'),
        ),
        migrations.AddIndex(
            model_name='memoryreviewaction',
            index=models.Index(fields=['action', '-created_at'], name='memory_memo_action_efebd2_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryreviewaction',
            index=models.Index(fields=['decision', '-created_at'], name='memory_memo_decisio_947487_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryreviewaction',
            index=models.Index(fields=['issue', '-created_at'], name='memory_memo_issue_i_630b93_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryreviewaction',
            index=models.Index(fields=['search_document', '-created_at'], name='memory_memo_search__30e520_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryreviewaction',
            index=models.Index(fields=['source_object', '-created_at'], name='memory_memo_source__332a46_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryreviewaction',
            index=models.Index(fields=['actor', '-created_at'], name='memory_memo_actor_i_4eaa5f_idx'),
        ),
    ]
