# Generated by Django 5.2.12 on 2026-05-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0010_memoryreviewaction_memoryingestionissue_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorysource',
            name='status',
            field=models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('missing_adapter', 'Missing adapter'), ('error', 'Error')], default='enabled', max_length=16),
        ),
    ]
