# Generated by Django 5.2.12 on 2026-05-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0011_alter_memorysource_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoryaccessaudit',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Аудит доступа к памяти', 'verbose_name_plural': 'Аудит доступа к памяти'},
        ),
        migrations.AlterModelOptions(
            name='memoryevalcase',
            options={'ordering': ['suite', 'code'], 'verbose_name': 'Тестовый кейс памяти', 'verbose_name_plural': 'Тестовые кейсы памяти'},
        ),
        migrations.AlterModelOptions(
            name='memorygraphentity',
            options={'ordering': ['entity_type', 'canonical_name'], 'verbose_name': 'Сущность графа памяти', 'verbose_name_plural': 'Сущности графа памяти'},
        ),
        migrations.AlterModelOptions(
            name='memorygraphextractionrun',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Запуск извлечения графа памяти', 'verbose_name_plural': 'Запуски извлечения графа памяти'},
        ),
        migrations.AlterModelOptions(
            name='memorygraphreviewitem',
            options={'ordering': ['status', '-created_at', '-id'], 'verbose_name': 'Элемент ревью графа памяти', 'verbose_name_plural': 'Элементы ревью графа памяти'},
        ),
        migrations.AlterModelOptions(
            name='memorygraphschemaproposal',
            options={'ordering': ['status', '-created_at', '-id'], 'verbose_name': 'Предложение схемы графа памяти', 'verbose_name_plural': 'Предложения схемы графа памяти'},
        ),
        migrations.AlterModelOptions(
            name='memoryindexjob',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Задание индекса памяти', 'verbose_name_plural': 'Задания индекса памяти'},
        ),
        migrations.AlterModelOptions(
            name='memoryingestionissue',
            options={'ordering': ['status', '-created_at', '-id'], 'verbose_name': 'Проблема загрузки памяти', 'verbose_name_plural': 'Проблемы загрузки памяти'},
        ),
        migrations.AlterModelOptions(
            name='memoryingestionrun',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Запуск загрузки памяти', 'verbose_name_plural': 'Запуски загрузки памяти'},
        ),
        migrations.AlterModelOptions(
            name='memoryknowledgecandidate',
            options={'ordering': ['status', '-created_at', '-id'], 'verbose_name': 'Кандидат знания памяти', 'verbose_name_plural': 'Кандидаты знаний памяти'},
        ),
        migrations.AlterModelOptions(
            name='memoryknowledgeevent',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Событие знания памяти', 'verbose_name_plural': 'События знаний памяти'},
        ),
        migrations.AlterModelOptions(
            name='memoryknowledgeitem',
            options={'ordering': ['scope', 'owner_user_id', '-updated_at', '-id'], 'verbose_name': 'Элемент знания памяти', 'verbose_name_plural': 'Элементы знаний памяти'},
        ),
        migrations.AlterModelOptions(
            name='memoryreflectionrun',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Запуск рефлексии памяти', 'verbose_name_plural': 'Запуски рефлексии памяти'},
        ),
        migrations.AlterModelOptions(
            name='memoryreviewaction',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('view_review_queue', 'Может просматривать очередь ревью памяти'), ('review_issues', 'Может ревьюировать проблемы памяти'), ('review_privacy_issues', 'Может ревьюировать проблемы приватности памяти'), ('manage_search_index', 'Может управлять поисковым индексом памяти'), ('view_memory_access_audit', 'Может просматривать аудит доступа к памяти')], 'verbose_name': 'Действие ревью памяти', 'verbose_name_plural': 'Действия ревью памяти'},
        ),
        migrations.AlterModelOptions(
            name='memorysearchdocument',
            options={'ordering': ['corpus_type', 'document_id'], 'verbose_name': 'Поисковый документ памяти', 'verbose_name_plural': 'Поисковые документы памяти'},
        ),
        migrations.AlterModelOptions(
            name='memorysource',
            options={'ordering': ['code'], 'verbose_name': 'Источник памяти', 'verbose_name_plural': 'Источники памяти'},
        ),
        migrations.AlterModelOptions(
            name='memorysourceobject',
            options={'ordering': ['source__code', 'relative_path'], 'verbose_name': 'Объект источника памяти', 'verbose_name_plural': 'Объекты источников памяти'},
        ),
        migrations.AlterModelOptions(
            name='memorywriterequest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Запрос записи памяти', 'verbose_name_plural': 'Запросы записи памяти'},
        ),
        migrations.AlterModelOptions(
            name='secretaccessaudit',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Аудит доступа к секрету', 'verbose_name_plural': 'Аудит доступа к секретам'},
        ),
        migrations.AlterModelOptions(
            name='secrethandle',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Ссылка на секрет', 'verbose_name_plural': 'Ссылки на секреты'},
        ),
        migrations.AlterField(
            model_name='memoryevalcase',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('disabled', 'Отключен')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='memorygraphextractionrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='memorygraphreviewitem',
            name='item_kind',
            field=models.CharField(choices=[('unknown_type', 'Неизвестный тип'), ('unknown_relation', 'Неизвестная связь'), ('low_confidence', 'Низкая уверенность'), ('canonicalization_conflict', 'Конфликт каноникализации'), ('dlp_warning', 'Предупреждение DLP')], max_length=64),
        ),
        migrations.AlterField(
            model_name='memorygraphreviewitem',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('needs_expert_review', 'Нужен эксперт'), ('resolved', 'Закрыт'), ('rejected', 'Отклонен')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='memorygraphschemaproposal',
            name='proposal_kind',
            field=models.CharField(choices=[('entity_type', 'Тип сущности'), ('relation_type', 'Тип связи'), ('attribute_type', 'Тип атрибута'), ('canonicalization_rule', 'Правило каноникализации'), ('forbidden_pattern', 'Запрещенный паттерн')], max_length=64),
        ),
        migrations.AlterField(
            model_name='memorygraphschemaproposal',
            name='status',
            field=models.CharField(choices=[('proposed', 'Предложено'), ('needs_expert_review', 'Нужен эксперт'), ('expert_approved', 'Одобрено экспертом'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('superseded', 'Заменено')], default='proposed', max_length=32),
        ),
        migrations.AlterField(
            model_name='memoryindexjob',
            name='job_kind',
            field=models.CharField(choices=[('discover', 'Обнаружение'), ('sync', 'Синхронизация'), ('reindex', 'Переиндексация'), ('eval', 'Оценка'), ('remember', 'Запоминание'), ('reflect', 'Рефлексия')], max_length=16),
        ),
        migrations.AlterField(
            model_name='memoryindexjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='memoryingestionissue',
            name='issue_kind',
            field=models.CharField(choices=[('encrypted_file', 'Зашифрованный файл'), ('unsupported_format', 'Неподдерживаемый формат'), ('file_too_large', 'Файл слишком большой'), ('partial_indexed', 'Частично проиндексировано'), ('parser_timeout', 'Тайм-аут парсера'), ('ocr_timeout', 'Тайм-аут OCR'), ('pii_blocked', 'Персональные данные заблокированы'), ('pii_audit', 'Аудит персональных данных'), ('secret_blocked', 'Секрет заблокирован'), ('acl_unresolved', 'ACL не разрешен'), ('schema_unknown_type', 'Неизвестный тип схемы'), ('schema_unknown_relation', 'Неизвестная связь схемы'), ('canonicalization_conflict', 'Конфликт каноникализации'), ('index_failed', 'Ошибка индекса'), ('index_stale', 'Индекс устарел'), ('fts_missing', 'Нет FTS'), ('vector_missing', 'Нет вектора'), ('source_deleted_index_left', 'Источник удален, индекс остался')], max_length=64),
        ),
        migrations.AlterField(
            model_name='memoryingestionissue',
            name='severity',
            field=models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('blocker', 'Блокер')], default='warning', max_length=16),
        ),
        migrations.AlterField(
            model_name='memoryingestionissue',
            name='status',
            field=models.CharField(choices=[('open', 'Открыта'), ('acknowledged', 'Принята к сведению'), ('needs_expert_review', 'Нужен эксперт'), ('resolved', 'Закрыта'), ('ignored', 'Игнорируется')], default='open', max_length=32),
        ),
        migrations.AlterField(
            model_name='memoryingestionrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='memoryknowledgecandidate',
            name='status',
            field=models.CharField(choices=[('proposed', 'Предложено'), ('needs_review', 'Нужно ревью'), ('accepted', 'Принято'), ('rejected', 'Отклонено'), ('merged', 'Объединено'), ('superseded', 'Заменено')], default='proposed', max_length=32),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeevent',
            name='event_type',
            field=models.CharField(choices=[('remembered', 'Запомнено'), ('edited', 'Изменено'), ('deleted', 'Удалено'), ('reflected', 'Отрефлексировано'), ('promoted', 'Повышено'), ('rejected', 'Отклонено'), ('secret_captured', 'Секрет зафиксирован')], max_length=32),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeitem',
            name='kind',
            field=models.CharField(choices=[('fact', 'Факт'), ('preference', 'Предпочтение'), ('procedure', 'Процедура'), ('decision', 'Решение'), ('secret_reference', 'Ссылка на секрет')], default='fact', max_length=32),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeitem',
            name='scope',
            field=models.CharField(choices=[('personal', 'Личное'), ('organization', 'Организационное')], max_length=32),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeitem',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('deleted', 'Удалено'), ('superseded', 'Заменено'), ('quarantined', 'Карантин')], default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='memoryreflectionrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('succeeded', 'Успешно'), ('failed', 'Ошибка')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='memoryreviewaction',
            name='action',
            field=models.CharField(choices=[('acknowledge', 'Принять к сведению'), ('assign', 'Назначить'), ('request_expert_review', 'Запросить эксперта'), ('resolve', 'Закрыть'), ('ignore', 'Игнорировать'), ('reopen', 'Открыть снова'), ('comment', 'Комментарий'), ('dry_run_reindex', 'Пробная переиндексация'), ('enqueue_reindex', 'Поставить переиндексацию в очередь'), ('retry_index', 'Повторить индексацию'), ('delete_stale_index', 'Удалить устаревший индекс'), ('mark_index_cleaned', 'Отметить индекс очищенным'), ('create_issue', 'Создать проблему')], max_length=40),
        ),
        migrations.AlterField(
            model_name='memoryreviewaction',
            name='decision',
            field=models.CharField(choices=[('applied', 'Применено'), ('queued', 'В очереди'), ('rejected', 'Отклонено'), ('failed', 'Ошибка'), ('info', 'Информация')], default='applied', max_length=32),
        ),
        migrations.AlterField(
            model_name='memorysearchdocument',
            name='corpus_type',
            field=models.CharField(choices=[('knowledge', 'Знания'), ('source_data', 'Исходные данные')], max_length=32),
        ),
        migrations.AlterField(
            model_name='memorysearchdocument',
            name='index_status',
            field=models.CharField(choices=[('indexing_pending', 'Ожидает индексации'), ('ready', 'Готов'), ('deleted', 'Удален'), ('failed', 'Ошибка')], default='indexing_pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='memorysearchdocument',
            name='object_kind',
            field=models.CharField(choices=[('knowledge_item', 'Элемент знания'), ('source_object', 'Объект источника'), ('summary', 'Сводка'), ('analytics_slice', 'Аналитический срез')], max_length=64),
        ),
        migrations.AlterField(
            model_name='memorysource',
            name='authority_class',
            field=models.CharField(blank=True, choices=[('system_of_record', 'Система-источник истины'), ('approved_corpus', 'Утвержденный корпус'), ('approved_user_memory', 'Утвержденная пользовательская память'), ('reviewed_org_knowledge', 'Проверенное организационное знание'), ('external_observation', 'Внешнее наблюдение'), ('candidate_input', 'Кандидатский ввод')], max_length=64),
        ),
        migrations.AlterField(
            model_name='memorysource',
            name='status',
            field=models.CharField(choices=[('enabled', 'Включен'), ('disabled', 'Отключен'), ('missing_adapter', 'Нет адаптера'), ('error', 'Ошибка')], default='enabled', max_length=16),
        ),
        migrations.AlterField(
            model_name='memorysource',
            name='trust_status',
            field=models.CharField(blank=True, choices=[('trusted', 'Доверенный'), ('review_required', 'Требует ревью'), ('candidate_only', 'Только кандидат'), ('quarantined', 'Карантин'), ('blocked', 'Заблокирован')], max_length=32),
        ),
        migrations.AlterField(
            model_name='memorysourceobject',
            name='discovery_status',
            field=models.CharField(choices=[('seen', 'Найден'), ('missing', 'Отсутствует'), ('changed', 'Изменен'), ('error', 'Ошибка')], default='seen', max_length=16),
        ),
        migrations.AlterField(
            model_name='memorysourceobject',
            name='ingestion_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('ready', 'Готов'), ('ingested', 'Загружен'), ('partial', 'Частично'), ('skipped', 'Пропущен'), ('failed', 'Ошибка')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='memorywriterequest',
            name='status',
            field=models.CharField(choices=[('queued', 'В очереди'), ('processing', 'Обрабатывается'), ('accepted', 'Принято'), ('candidate_created', 'Кандидат создан'), ('failed', 'Ошибка'), ('cancelled', 'Отменено')], default='queued', max_length=32),
        ),
        migrations.AlterField(
            model_name='memorywriterequest',
            name='target_scope',
            field=models.CharField(choices=[('personal', 'Личная'), ('organization', 'Организационная')], default='personal', max_length=32),
        ),
        migrations.AlterField(
            model_name='secretaccessaudit',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('link', 'Связь'), ('rotate', 'Ротация'), ('revoke', 'Отзыв'), ('service_resolve', 'Сервисное разрешение')], max_length=32),
        ),
        migrations.AlterField(
            model_name='secretaccessaudit',
            name='decision',
            field=models.CharField(choices=[('allowed', 'Разрешено'), ('denied', 'Запрещено'), ('failed', 'Ошибка')], max_length=32),
        ),
        migrations.AlterField(
            model_name='secrethandle',
            name='provider',
            field=models.CharField(choices=[('external_vault_link', 'Ссылка на внешнее хранилище'), ('disabled', 'Отключено'), ('local_stub', 'Локальная заглушка'), ('openbao', 'OpenBao')], default='external_vault_link', max_length=64),
        ),
        migrations.AlterField(
            model_name='secrethandle',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('revoked', 'Отозван'), ('unavailable', 'Недоступен')], default='active', max_length=32),
        ),
    ]
