# Generated by Django 5.2.13 on 2026-06-09 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_alter_agentactionlog_options_and_more'),
        ('memory', '0013_memoryfileobject_memoryfileobjectversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryknowledgeitem',
            name='source_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memory_knowledge_items', to='ai.chatsession'),
        ),
        migrations.AlterField(
            model_name='memorywriterequest',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_write_requests', to='ai.chatsession'),
        ),
    ]
