# Generated by Django 5.2.13 on 2026-06-09 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_alter_agentactionlog_options_and_more'),
        ('memory', '0014_alter_memoryknowledgeitem_source_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorywriterequest',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memory_write_requests', to='ai.chatsession'),
        ),
    ]
