# Generated by Django 5.2.12 on 2026-06-15 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_alter_agentactionlog_actor_and_more'),
        ('memory', '0015_alter_memorywriterequest_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryaccessaudit',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_access_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryfilemovejob',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_memory_file_move_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryfileorganizationdecision',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_file_organization_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryfileorganizationproposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_memory_file_organization_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryfileusageevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_file_usage_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryfilevirtualplacement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_file_virtual_placements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryfilevirtualview',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_file_virtual_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorygraphreviewitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_graph_review_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorygraphschemaproposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_graph_schema_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryindexjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_index_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryingestionissue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_memory_ingestion_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryingestionissue',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_memory_ingestion_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryingestionrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_ingestion_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgecandidate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgecandidate',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_candidate_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_knowledge_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_memory_knowledge_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeitem',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_knowledge_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryknowledgeitem',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_knowledge_items', to='ai.chatsession'),
        ),
        migrations.AlterField(
            model_name='memoryreflectionrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memory_reflection_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memoryreviewaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_review_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorywriterequest',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory_write_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memorywriterequest',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_write_requests', to='ai.chatsession'),
        ),
        migrations.AlterField(
            model_name='secretaccessaudit',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secret_access_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secrethandle',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_secret_handles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secrethandle',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secret_handles', to=settings.AUTH_USER_MODEL),
        ),
    ]
