# Generated by Django 5.2.12 on 2026-06-15 19:22

import uuid
from django.db import migrations, models


def create_postgresql_fulltext_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    table = schema_editor.quote_name("memory_memoryfulltextindex")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            CREATE INDEX IF NOT EXISTS memory_fulltext_search_text_gin
            ON {table}
            USING GIN (to_tsvector('simple', coalesce(search_text, '')))
            """
        )


def drop_postgresql_fulltext_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS memory_fulltext_search_text_gin")


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0016_alter_memoryaccessaudit_actor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryExternalConnectorJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('source_code', models.CharField(max_length=120)),
                ('job_kind', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=32)),
                ('priority', models.IntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Задание внешнего коннектора',
                'verbose_name_plural': 'Задания внешних коннекторов',
                'ordering': ['-priority', 'created_at', 'job_id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at', 'locked_until', '-priority', 'created_at'], name='memory_memo_status_2a9a9c_idx'), models.Index(fields=['source_code', 'status', 'created_at'], name='memory_memo_source__c9db5d_idx'), models.Index(fields=['idempotency_key'], name='memory_memo_idempot_71a700_idx'), models.Index(fields=['job_id'], name='memory_memo_job_id_7b0b25_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryFullTextIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=180, unique=True)),
                ('search_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scope_tokens', models.JSONField(blank=True, default=list)),
                ('sensitivity', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('backend_schema_version', models.CharField(default='postgres-fts-v1', max_length=64)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Полнотекстовый индекс памяти',
                'verbose_name_plural': 'Полнотекстовые индексы памяти',
                'ordering': ['document_id'],
                'indexes': [models.Index(fields=['document_id'], name='memory_memo_documen_9759f3_idx'), models.Index(fields=['is_active', 'sensitivity'], name='memory_memo_is_acti_4b04f7_idx'), models.Index(fields=['indexed_at'], name='memory_memo_indexed_b6fe50_idx')],
            },
        ),
        migrations.RunPython(create_postgresql_fulltext_index, drop_postgresql_fulltext_index),
    ]
