# Generated by Django 5.2.12 on 2026-07-04 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0018_archive_legacy_memory_queues'),
    ]

    operations = [
        # NOTE: unlike autodetector output, this intentionally skips the
        # individual RemoveField operations for fields on MemoryIndexJob /
        # MemoryKnowledgeEvent / MemoryReflectionRun / MemoryWriteRequest:
        # those models are deleted outright below via DeleteModel, and on
        # SQLite an intermediate RemoveField forces a table "remake" that
        # tries to recreate the model's declared Meta.indexes (e.g.
        # MemoryKnowledgeEvent's ["actor", "created_at"] index) against a
        # state where the field has already been removed, which raises
        # FieldDoesNotExist. Dropping the whole table via DeleteModel avoids
        # that intermediate state entirely and is equivalent on PostgreSQL.
        migrations.AlterField(
            model_name='memoryreviewaction',
            name='index_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_actions', to='memory.memoryexternalconnectorjob'),
        ),
        migrations.AlterModelOptions(
            name='memoryexternalconnectorjob',
            options={'ordering': ['-priority', 'created_at', 'job_id'], 'verbose_name': 'Задание очереди памяти', 'verbose_name_plural': 'Задания очереди памяти'},
        ),
        migrations.AddField(
            model_name='memoryexternalconnectorjob',
            name='locked_by',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='memoryexternalconnectorjob',
            name='source_code',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='memoryexternalconnectorjob',
            index=models.Index(fields=['job_kind', 'status', 'created_at'], name='memory_memo_job_kin_8e1073_idx'),
        ),
        migrations.DeleteModel(
            name='MemoryIndexJob',
        ),
        migrations.DeleteModel(
            name='MemoryKnowledgeEvent',
        ),
        migrations.DeleteModel(
            name='MemoryReflectionRun',
        ),
        migrations.DeleteModel(
            name='MemoryWriteRequest',
        ),
    ]
