# Generated by Django 5.2.13 on 2026-04-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260423_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('distinguished_name', models.CharField(db_index=True, max_length=1024, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(help_text='Уровень вложенности (2-5)')),
                ('dn_level_1', models.CharField(blank=True, db_index=True, help_text='Организация (уровень 1)', max_length=255, null=True)),
                ('dn_level_2', models.CharField(blank=True, db_index=True, help_text='Подразделение (уровень 2)', max_length=255, null=True)),
                ('dn_level_3', models.CharField(blank=True, db_index=True, help_text='Отдел (уровень 3)', max_length=255, null=True)),
                ('dn_level_4', models.CharField(blank=True, help_text='Подотдел (уровень 4)', max_length=255, null=True)),
                ('dn_level_5', models.CharField(blank=True, help_text='Группа (уровень 5)', max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('ad_last_modified', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Родительская OU', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.organizationalunit')),
            ],
            options={
                'verbose_name': 'Организационная единица',
                'verbose_name_plural': 'Организационные единицы',
                'ordering': ['level', 'name'],
                'indexes': [models.Index(fields=['level'], name='core_organi_level_b2f169_idx'), models.Index(fields=['dn_level_1'], name='core_organi_dn_leve_674b3d_idx'), models.Index(fields=['dn_level_2'], name='core_organi_dn_leve_05700f_idx'), models.Index(fields=['parent'], name='core_organi_parent__de0ded_idx')],
            },
        ),
    ]
