# Generated by Django 5.2.13 on 2026-04-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_organizational_unit'),
        ('core', '0003_organizationalunit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationalUnit',
        ),
    ]
