# Generated by Django 5.2.12 on 2026-03-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('serial_number', models.CharField(max_length=128, unique=True, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, max_length=128, verbose_name='Инвентарный номер')),
                ('department', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Местоположение')),
                ('operational_status', models.CharField(choices=[('active', 'В эксплуатации'), ('maintenance', 'На обслуживании'), ('reserved', 'Резерв'), ('decommissioned', 'Выведено из эксплуатации')], default='active', max_length=32, verbose_name='Статус эксплуатации')),
                ('commissioned_at', models.DateField(blank=True, null=True, verbose_name='Дата ввода')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Медицинское изделие',
                'verbose_name_plural': 'Медицинские изделия',
                'ordering': ['name', 'serial_number'],
            },
        ),
    ]
