# Generated by Django 5.2.12 on 2026-03-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldevice',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивации'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
    ]
