# Generated by Django 5.2.12 on 2026-03-18 10:45

from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_departments(apps, schema_editor):
    Department = apps.get_model("core", "Department")
    MedicalDevice = apps.get_model("inventory", "MedicalDevice")

    department_map = {}
    for raw_name in MedicalDevice.objects.order_by().values_list("department", flat=True).distinct():
        normalized = (raw_name or "").strip()
        if not normalized:
            continue
        department, _ = Department.objects.get_or_create(name=normalized, parent=None)
        department_map[normalized.lower()] = department.id

    for device in MedicalDevice.objects.all():
        normalized = (device.department or "").strip()
        if normalized:
            device.department_ref_id = department_map[normalized.lower()]
            device.save(update_fields=["department_ref"])


def backwards_copy_departments(apps, schema_editor):
    MedicalDevice = apps.get_model("inventory", "MedicalDevice")

    for device in MedicalDevice.objects.select_related("department_ref"):
        if device.department_ref_id:
            device.department = device.department_ref.name
            device.save(update_fields=["department"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0002_medicaldevice_archived_at_medicaldevice_is_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicaldevice",
            name="department_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.department",
                verbose_name="Подразделение",
            ),
        ),
        migrations.RunPython(forwards_copy_departments, backwards_copy_departments),
        migrations.RemoveField(
            model_name="medicaldevice",
            name="department",
        ),
        migrations.RenameField(
            model_name="medicaldevice",
            old_name="department_ref",
            new_name="department",
        ),
        migrations.AlterField(
            model_name="medicaldevice",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="medical_devices",
                to="core.department",
                verbose_name="Подразделение",
            ),
        ),
    ]
