# Generated by Django 5.2.12 on 2026-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_department_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldevice',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Архивировано'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='operational_status',
            field=models.CharField(choices=[('active', 'В эксплуатации'), ('maintenance', 'На обслуживании'), ('reserved', 'Резерв'), ('decommissioned', 'Выведено из эксплуатации')], db_index=True, default='active', max_length=32, verbose_name='Статус эксплуатации'),
        ),
    ]
