# Generated by Django 5.2.12 on 2026-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_department_unique_together_and_more'),
        ('inventory', '0004_add_db_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldevice',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Архивировано'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='operational_status',
            field=models.CharField(choices=[('active', 'В эксплуатации'), ('maintenance', 'На обслуживании'), ('reserved', 'Резерв'), ('decommissioned', 'Выведено из эксплуатации')], default='active', max_length=32, verbose_name='Статус эксплуатации'),
        ),
        migrations.AddIndex(
            model_name='medicaldevice',
            index=models.Index(fields=['operational_status'], name='inventory_m_operati_58e1fc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldevice',
            index=models.Index(fields=['is_archived'], name='inventory_m_is_arch_2cba74_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldevice',
            index=models.Index(fields=['department', 'is_archived'], name='inventory_m_departm_152b7c_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicaldevice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('is_archived', False)), models.Q(('archived_at__isnull', False), ('is_archived', True)), _connector='OR'), name='device_archive_consistent'),
        ),
    ]
