# Generated by Django 5.2.13 on 2026-06-19 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_department_unique_together_and_more'),
        ('inventory', '0005_alter_medicaldevice_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldevice',
            name='building',
            field=models.CharField(blank=True, max_length=64, verbose_name='Здание'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='decommission_reason',
            field=models.TextField(blank=True, verbose_name='Причина вывода из эксплуатации'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='decommissioned_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вывода из эксплуатации'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='device_type',
            field=models.CharField(blank=True, help_text='Например: рентгеновский аппарат, УЗИ-сканер, ИВЛ и т. п.', max_length=128, verbose_name='Тип медицинского изделия'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='floor',
            field=models.CharField(blank=True, max_length=32, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='production_country',
            field=models.CharField(blank=True, max_length=128, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='registration_certificate_number',
            field=models.CharField(blank=True, max_length=128, verbose_name='Номер регистрационного удостоверения'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='room',
            field=models.CharField(blank=True, max_length=64, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='medicaldevice',
            name='service_life_years',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Нормативный срок службы или годности в годах.', null=True, verbose_name='Срок службы/годности, лет'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='commissioned_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_devices', to='core.department', verbose_name='Структурное подразделение'),
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Местоположение (legacy)'),
        ),
        migrations.AddIndex(
            model_name='medicaldevice',
            index=models.Index(fields=['registration_certificate_number'], name='inventory_m_registr_7d44df_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldevice',
            index=models.Index(fields=['inventory_number'], name='inventory_m_invento_677ec8_idx'),
        ),
    ]
