# Generated by Django 5.2.12 on 2026-07-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_medicaldevice_serial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaldevice',
            options={'ordering': ['name', 'inventory_number', 'id'], 'verbose_name': 'Медицинское изделие', 'verbose_name_plural': 'Медицинские изделия'},
        ),
        migrations.AlterField(
            model_name='medicaldevice',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='Инвентарный номер'),
        ),
    ]
