from apps.settings_center.descriptors import SettingDescriptor


def get_settings_descriptors():
    return [
        SettingDescriptor(
            setting_id="ai.contract.registry",
            domain="ai",
            section="Реестр",
            title="Контракт реестра ИИ",
            description="Рабочий контракт ИИ-реестра: идентичность оркестратора, каталог задач и ссылки на каталог инструментов.",
            help_topic_id="settings.ai.contract.registry",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            metadata={
                "settings_path": "LOCAL_BUSINESS_AI_REGISTRY_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_AI_REGISTRY",
                "validator": "validate_ai_registry_payload",
            },
        ),
        SettingDescriptor(
            setting_id="ai.contract.tools",
            domain="ai",
            section="Инструменты",
            title="Контракт инструментов ИИ",
            description="Рабочий контракт каталога инструментов. Расхождения по-прежнему проверяются командой validate_architecture_contracts.",
            help_topic_id="settings.ai.contract.tools",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            metadata={
                "settings_path": "LOCAL_BUSINESS_AI_TOOLS_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_AI_TOOLS",
                "validator": "validate_ai_tools_payload",
            },
        ),
        SettingDescriptor(
            setting_id="ai.contract.task_types",
            domain="ai",
            section="Задачи",
            title="Контракт типов задач ИИ",
            description="Рабочий каталог типов задач для управления доступностью инструментов и политикой подтверждений.",
            help_topic_id="settings.ai.contract.task_types",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            metadata={
                "settings_path": "LOCAL_BUSINESS_AI_TASK_TYPES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_AI_TASK_TYPES",
                "validator": "validate_ai_task_types_payload",
            },
        ),
        SettingDescriptor(
            setting_id="ai.contract.models",
            domain="ai",
            section="Модели",
            title="Профили моделей ИИ",
            description="Контракт профилей моделей виден здесь; детальная проверка маршрутизации моделей будет добавлена вместе с поставщиками моделей.",
            help_topic_id="settings.ai.contract.models",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="read_only",
            metadata={"settings_path": "LOCAL_BUSINESS_AI_MODELS_FILE"},
        ),
        SettingDescriptor(
            setting_id="ai.contract.chat_settings",
            domain="ai",
            section="Чат",
            title="Настройки ИИ-чата",
            description="Общие рабочие настройки для полноэкранного ИИ-чата и чата в боковой панели.",
            help_topic_id="settings.ai.contract.chat_settings",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            metadata={
                "settings_path": "LOCAL_BUSINESS_AI_CHAT_SETTINGS_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_AI_CHAT_SETTINGS",
                "validator": "validate_ai_chat_settings_payload",
            },
        ),
    ]
