from apps.settings_center.descriptors import SettingDescriptor


def get_settings_descriptors():
    return [
        SettingDescriptor(
            setting_id="memory.contract.sources",
            domain="memory",
            section="Sources",
            title="Memory sources",
            description="Runtime source catalog for model, document, UNC, local path and external snapshot memory sources.",
            help_topic_id="settings.memory.contract.sources",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            requires_reindex=True,
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_SOURCES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_SOURCES",
                "validator": "validate_memory_sources_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.profiles",
            domain="memory",
            section="Profiles",
            title="Memory profiles",
            description="Chunking, extraction, embedding, index and ranking profiles for memory retrieval.",
            help_topic_id="settings.memory.contract.profiles",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            requires_reindex=True,
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_PROFILES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_PROFILES",
                "validator": "validate_memory_profiles_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.routing",
            domain="memory",
            section="Routing",
            title="Memory routing",
            description="Sensitivity routing and cloud gate rules for memory-backed AI context.",
            help_topic_id="settings.memory.contract.routing",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_ROUTING_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_ROUTING",
                "validator": "validate_memory_routing_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.trust_policy",
            domain="memory",
            section="Security",
            title="Memory trust policy",
            description="Trusted source defaults and direct context eligibility rules for memory retrieval.",
            help_topic_id="settings.memory.contract.trust_policy",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            requires_reindex=True,
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_TRUST_POLICY_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_TRUST_POLICY",
                "validator": "validate_memory_trust_policy_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.claims_policy",
            domain="memory",
            section="Governance",
            title="Memory claims policy",
            description="Future-stage claim and belief lifecycle policy. MVP memory uses MemoryKnowledgeItem directly.",
            help_topic_id="settings.memory.contract.claims_policy",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            requires_reindex=False,
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_CLAIMS_POLICY_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_CLAIMS_POLICY",
                "validator": "validate_memory_claims_policy_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.retrieval_budget",
            domain="memory",
            section="Retrieval",
            title="Memory retrieval budget",
            description="Deterministic hot-path retrieval limits and optional local LLM rerank guardrails.",
            help_topic_id="settings.memory.contract.retrieval_budget",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_RETRIEVAL_BUDGET_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_RETRIEVAL_BUDGET",
                "validator": "validate_memory_retrieval_budget_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.ingestion_profiles",
            domain="memory",
            section="Processing",
            title="Memory ingestion profiles",
            description="Adapter, parser, OCR, limits, raw mode, ACL and issue policy profiles for corporate documents.",
            help_topic_id="settings.memory.contract.ingestion_profiles",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            requires_reindex=True,
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_INGESTION_PROFILES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_INGESTION_PROFILES",
                "validator": "validate_memory_ingestion_profiles_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.source.acl_mode",
            domain="memory",
            section="Access",
            title="Source ACL mode",
            description="Controls whether a file-backed memory source uses source scope rules or inherited filesystem ACLs.",
            help_topic_id="settings.memory.source.acl_mode",
            storage_kind="runtime_contract",
            value_type="choice",
            widget="select",
            write_policy="requires_domain_workflow",
            requires_reindex=True,
            choices=("scope_rule", "inherit_source_acl", "inherit_source_acl_with_fallback"),
        ),
        SettingDescriptor(
            setting_id="memory.contract.graph_schema",
            domain="memory",
            section="Graph",
            title="Memory graph schema",
            description="Moderated graph schema contract for extracted entities and facts.",
            help_topic_id="settings.memory.contract.graph_schema",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_GRAPH_SCHEMA_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_GRAPH_SCHEMA",
                "validator": "validate_memory_graph_schema_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.secret.external_vault_link",
            domain="memory",
            section="Secrets",
            title="External secret links",
            description="Vaultwarden-style SecretHandle metadata for API keys and credentials. Raw secret values are never stored in contracts or audit.",
            help_topic_id="settings.memory.secret.external_vault_link",
            storage_kind="secret_handle",
            value_type="object",
            widget="secret_handle",
            write_policy="secret_handle_only",
            sensitivity="secret",
        ),
    ]
