from apps.settings_center.descriptors import SettingDescriptor


def get_settings_descriptors():
    return [
        SettingDescriptor(
            setting_id="memory.contract.sources",
            domain="memory",
            section="Источники",
            title="Источники памяти",
            description="Рабочий каталог источников памяти: модели, документы, UNC-пути, локальные папки и внешние снимки.",
            help_topic_id="settings.memory.contract.sources",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            requires_reindex=True,
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_SOURCES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_SOURCES",
                "validator": "validate_memory_sources_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.profiles",
            domain="memory",
            section="Профили",
            title="Профили памяти",
            description="Профили разбиения, извлечения, векторизации, индексации и ранжирования для поиска по памяти.",
            help_topic_id="settings.memory.contract.profiles",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            requires_reindex=True,
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_PROFILES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_PROFILES",
                "validator": "validate_memory_profiles_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.routing",
            domain="memory",
            section="Маршрутизация",
            title="Маршрутизация памяти",
            description="Правила чувствительности и доступа к облачным моделям для ИИ-контекста из памяти.",
            help_topic_id="settings.memory.contract.routing",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_ROUTING_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_ROUTING",
                "validator": "validate_memory_routing_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.trust_policy",
            domain="memory",
            section="Безопасность",
            title="Политика доверия памяти",
            description="Значения доверия по умолчанию и правила допуска источников в прямой контекст памяти.",
            help_topic_id="settings.memory.contract.trust_policy",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            requires_reindex=True,
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_TRUST_POLICY_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_TRUST_POLICY",
                "validator": "validate_memory_trust_policy_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.claims_policy",
            domain="memory",
            section="Управление",
            title="Политика утверждений памяти",
            description="Будущая политика жизненного цикла утверждений и убеждений. В MVP память напрямую использует MemoryKnowledgeItem.",
            help_topic_id="settings.memory.contract.claims_policy",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            requires_reindex=False,
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_CLAIMS_POLICY_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_CLAIMS_POLICY",
                "validator": "validate_memory_claims_policy_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.retrieval_budget",
            domain="memory",
            section="Поиск",
            title="Бюджет поиска по памяти",
            description="Детерминированные ограничения быстрого поиска и защитные правила для опционального локального переранжирования.",
            help_topic_id="settings.memory.contract.retrieval_budget",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_RETRIEVAL_BUDGET_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_RETRIEVAL_BUDGET",
                "validator": "validate_memory_retrieval_budget_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.contract.ingestion_profiles",
            domain="memory",
            section="Обработка",
            title="Профили загрузки памяти",
            description="Профили адаптеров, парсеров, OCR, лимитов, режима исходных данных, ACL и политики проблем для корпоративных документов.",
            help_topic_id="settings.memory.contract.ingestion_profiles",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            requires_reindex=True,
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_INGESTION_PROFILES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_INGESTION_PROFILES",
                "validator": "validate_memory_ingestion_profiles_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.source.acl_mode",
            domain="memory",
            section="Доступ",
            title="Режим ACL источника",
            description="Определяет, использует ли файловый источник памяти собственные области доступа или наследует ACL файловой системы.",
            help_topic_id="settings.memory.source.acl_mode",
            storage_kind="runtime_contract",
            value_type="choice",
            widget="select",
            write_policy="requires_domain_workflow",
            requires_reindex=True,
            choices=("scope_rule", "inherit_source_acl", "inherit_source_acl_with_fallback"),
        ),
        SettingDescriptor(
            setting_id="memory.contract.graph_schema",
            domain="memory",
            section="Граф",
            title="Схема графа памяти",
            description="Модерируемый контракт схемы графа для извлеченных сущностей и фактов.",
            help_topic_id="settings.memory.contract.graph_schema",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            metadata={
                "settings_path": "LOCAL_BUSINESS_MEMORY_GRAPH_SCHEMA_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_MEMORY_GRAPH_SCHEMA",
                "validator": "validate_memory_graph_schema_payload",
            },
        ),
        SettingDescriptor(
            setting_id="memory.secret.external_vault_link",
            domain="memory",
            section="Секреты",
            title="Внешние ссылки на секреты",
            description="Метаданные SecretHandle для API-ключей и учетных данных. Исходные значения секретов не хранятся в контрактах и аудите.",
            help_topic_id="settings.memory.secret.external_vault_link",
            storage_kind="secret_handle",
            value_type="object",
            widget="secret_handle",
            write_policy="secret_handle_only",
            sensitivity="secret",
        ),
    ]
