# Generated by Django 5.2.6 on 2026-03-20 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("external_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("channel", models.CharField(choices=[("internal", "Internal"), ("librechat", "LibreChat")], default="internal", max_length=32)),
                ("status", models.CharField(choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=32)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ai_chat_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "AI chat session",
                "verbose_name_plural": "AI chat sessions",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System"), ("tool", "Tool")], max_length=16)),
                ("content", models.TextField()),
                ("tool_name", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="ai.chatsession")),
            ],
            options={
                "verbose_name": "AI chat message",
                "verbose_name_plural": "AI chat messages",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="AgentActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tool_code", models.CharField(max_length=120)),
                ("action_kind", models.CharField(choices=[("read", "Read"), ("write", "Write"), ("admin", "Admin")], max_length=16)),
                ("status", models.CharField(choices=[("succeeded", "Succeeded"), ("denied", "Denied"), ("failed", "Failed")], max_length=16)),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ai_actions", to=settings.AUTH_USER_MODEL)),
                ("message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actions", to="ai.chatmessage")),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actions", to="ai.chatsession")),
            ],
            options={
                "verbose_name": "AI action log",
                "verbose_name_plural": "AI action logs",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
