# Generated by Django migration

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("tool_code", models.CharField(max_length=120)),
                ("action_kind", models.CharField(max_length=16)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("confirmed", "Confirmed"), ("cancelled", "Cancelled")], default="pending", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ai_pending_actions", to=settings.AUTH_USER_MODEL)),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="pending_actions", to="ai.chatsession")),
            ],
            options={
                "verbose_name": "AI pending action",
                "verbose_name_plural": "AI pending actions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AlterField(
            model_name="agentactionlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("succeeded", "Succeeded"),
                    ("denied", "Denied"),
                    ("failed", "Failed"),
                    ("pending", "Pending"),
                ],
                max_length=16,
            ),
        ),
    ]
