# Generated by Django 5.2.12 on 2026-05-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_chatattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='channel',
            field=models.CharField(choices=[('internal', 'Internal')], default='internal', max_length=32),
        ),
    ]
