# Generated by Django 5.2.12 on 2026-05-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_remove_librechat_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentactionlog',
            name='action_kind',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='agentactionlog',
            name='tool_code',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='tool_code',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
