# Generated by Django 5.2.12 on 2026-05-14 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_add_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentactionlog',
            name='action_kind',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('admin', 'Admin')], max_length=16),
        ),
        migrations.AlterField(
            model_name='agentactionlog',
            name='tool_code',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='tool_code',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='SlashCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Command name without the leading slash, e.g. 'summary'", max_length=64)),
                ('shortcut', models.CharField(blank=True, help_text="Optional short alias, e.g. 'sum'", max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('template', models.TextField(help_text='Prompt template. Use {input} as placeholder for user text after the command.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slash_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Слэш-команда',
                'verbose_name_plural': 'Слэш-команды',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
