# Generated by Django 5.2.12 on 2026-05-15 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_alter_agentactionlog_action_kind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slashcommand',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='agentactionlog',
            index=models.Index(fields=['-created_at', '-id'], name='ai_agentact_created_8995c3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentactionlog',
            index=models.Index(fields=['status'], name='ai_agentact_status_31b3e1_idx'),
        ),
        migrations.AddIndex(
            model_name='agentactionlog',
            index=models.Index(fields=['action_kind'], name='ai_agentact_action__bdc02c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentactionlog',
            index=models.Index(fields=['tool_code'], name='ai_agentact_tool_co_8a9064_idx'),
        ),
        migrations.AddIndex(
            model_name='chatattachment',
            index=models.Index(fields=['file_type'], name='ai_chatatta_file_ty_9dab05_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at', 'id'], name='ai_chatmess_created_c25b81_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='ai_chatmess_role_6b1042_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['-updated_at', '-id'], name='ai_chatsess_updated_ca8401_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status'], name='ai_chatsess_status_e970d8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['channel'], name='ai_chatsess_channel_26051b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['last_message_at'], name='ai_chatsess_last_me_3264f1_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingaction',
            index=models.Index(fields=['-created_at', '-id'], name='ai_pendinga_created_20dd43_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingaction',
            index=models.Index(fields=['status'], name='ai_pendinga_status_8e796b_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingaction',
            index=models.Index(fields=['tool_code'], name='ai_pendinga_tool_co_b1c63b_idx'),
        ),
        migrations.AddConstraint(
            model_name='slashcommand',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_slash_command_name_per_user'),
        ),
    ]
