# Generated by Codex on 2026-05-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0009_alter_agentactionlog_actor_alter_chatsession_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="channel",
            field=models.CharField(
                choices=[("internal", "Internal"), ("sidebar", "Sidebar")],
                default="internal",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="AIWindowContextSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("window_id", models.CharField(max_length=128)),
                ("context_version", models.PositiveIntegerField()),
                ("context_hash", models.CharField(max_length=96)),
                ("sanitized_envelope", models.JSONField(blank=True, default=dict)),
                ("resolved_summary", models.JSONField(blank=True, default=dict)),
                ("is_current", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_window_context_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI window context snapshot",
                "verbose_name_plural": "AI window context snapshots",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="aiwindowcontextsnapshot",
            index=models.Index(fields=["user", "window_id", "context_version"], name="ai_aiwindow_user_id_482744_idx"),
        ),
        migrations.AddIndex(
            model_name="aiwindowcontextsnapshot",
            index=models.Index(fields=["user", "window_id", "is_current"], name="ai_aiwindow_user_id_3dfa4a_idx"),
        ),
        migrations.AddIndex(
            model_name="aiwindowcontextsnapshot",
            index=models.Index(fields=["expires_at"], name="ai_aiwindow_expires_4dd8dc_idx"),
        ),
        migrations.AddConstraint(
            model_name="aiwindowcontextsnapshot",
            constraint=models.UniqueConstraint(
                fields=("user", "window_id", "context_version"),
                name="uniq_ai_window_context_version",
            ),
        ),
    ]
