# Generated by Django 5.2.12 on 2026-05-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_chatsession_sidebar_aiwindowcontextsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentactionlog',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Журнал действий ИИ', 'verbose_name_plural': 'Журнал действий ИИ'},
        ),
        migrations.AlterModelOptions(
            name='aiwindowcontextsnapshot',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Снимок контекста окна ИИ', 'verbose_name_plural': 'Снимки контекста окна ИИ'},
        ),
        migrations.AlterModelOptions(
            name='chatattachment',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Вложение чата', 'verbose_name_plural': 'Вложения чата'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'id'], 'verbose_name': 'Сообщение ИИ-чата', 'verbose_name_plural': 'Сообщения ИИ-чата'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-updated_at', '-id'], 'verbose_name': 'Сессия ИИ-чата', 'verbose_name_plural': 'Сессии ИИ-чата'},
        ),
        migrations.AlterModelOptions(
            name='pendingaction',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Ожидающее действие ИИ', 'verbose_name_plural': 'Ожидающие действия ИИ'},
        ),
        migrations.AlterField(
            model_name='agentactionlog',
            name='action_kind',
            field=models.CharField(choices=[('read', 'Чтение'), ('write', 'Запись'), ('admin', 'Администрирование')], max_length=16),
        ),
        migrations.AlterField(
            model_name='agentactionlog',
            name='status',
            field=models.CharField(choices=[('succeeded', 'Успешно'), ('denied', 'Отклонено'), ('failed', 'Ошибка'), ('pending', 'Ожидает')], max_length=16),
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='Размер файла в байтах'),
        ),
        migrations.AlterField(
            model_name='chatattachment',
            name='file_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('document', 'Документ'), ('audio', 'Аудио'), ('other', 'Другое')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('system', 'Система'), ('tool', 'Инструмент')], max_length=16),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='channel',
            field=models.CharField(choices=[('internal', 'Основной чат'), ('sidebar', 'Боковая панель')], default='internal', max_length=32),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('archived', 'В архиве')], default='active', max_length=32),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('expired', 'Истекло')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='slashcommand',
            name='name',
            field=models.CharField(help_text="Имя команды без начального слэша, например 'summary'.", max_length=64),
        ),
        migrations.AlterField(
            model_name='slashcommand',
            name='shortcut',
            field=models.CharField(blank=True, help_text="Необязательное короткое сокращение, например 'sum'.", max_length=16),
        ),
        migrations.AlterField(
            model_name='slashcommand',
            name='template',
            field=models.TextField(help_text='Шаблон промта. Используйте {input} как место для текста пользователя после команды.'),
        ),
    ]
