# Generated by Django 5.2.12 on 2026-06-15 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_alter_agentactionlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentactionlog',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiwindowcontextsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_window_context_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_pending_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='slashcommand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slash_commands', to=settings.AUTH_USER_MODEL),
        ),
    ]
