from apps.settings_center.descriptors import SettingDescriptor


def get_settings_descriptors():
    return [
        SettingDescriptor(
            setting_id="core.contract.role_rules",
            domain="core",
            section="Access",
            title="Role rules contract",
            description="Runtime role capability rules used by work order, navigation and management policies.",
            help_topic_id="settings.core.contract.role_rules",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            required_permission="settings_center.manage",
            metadata={
                "settings_path": "LOCAL_BUSINESS_ROLE_RULES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_ROLE_RULES",
                "validator": "validate_role_rules_payload",
            },
        ),
        SettingDescriptor(
            setting_id="core.contract.workflow_rules",
            domain="core",
            section="Workflow",
            title="Workflow rules contract",
            description="Runtime workflow statuses and transitions used by work order state changes.",
            help_topic_id="settings.core.contract.workflow_rules",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            required_permission="settings_center.manage",
            metadata={
                "settings_path": "LOCAL_BUSINESS_WORKFLOW_RULES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_WORKFLOW_RULES",
                "validator": "validate_workflow_rules_payload",
            },
        ),
        *env_descriptors(),
    ]


def env_descriptors():
    return [
        SettingDescriptor(
            setting_id="settings_center.env.DJANGO_AUTH_MODE",
            domain="env",
            section="Authentication",
            title="Django auth mode",
            description="Bootstrap authentication mode. Changing it requires process restart.",
            help_topic_id="settings.env.DJANGO_AUTH_MODE",
            storage_kind="env_var",
            value_type="choice",
            widget="select",
            write_policy="proposal_only",
            requires_restart=True,
            choices=("local", "ldap", "remote_user", "hybrid"),
            metadata={"env_key": "DJANGO_AUTH_MODE", "default": "hybrid"},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.SETTINGS_CENTER_ENV_APPLY_MODE",
            domain="env",
            section="Settings Center",
            title="Environment apply mode",
            description="Controls whether environment settings are read-only, proposal-only or local-file editable.",
            help_topic_id="settings.env.SETTINGS_CENTER_ENV_APPLY_MODE",
            storage_kind="env_var",
            value_type="choice",
            widget="select",
            write_policy="proposal_only",
            requires_restart=True,
            choices=("read_only", "proposal", "local_file"),
            metadata={"env_key": "SETTINGS_CENTER_ENV_APPLY_MODE", "default": "proposal"},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.AD_LDAP_HOST",
            domain="env",
            section="Active Directory",
            title="AD LDAP host",
            description="Domain controller host used by LDAP lookup and login backends.",
            help_topic_id="settings.env.AD_LDAP_HOST",
            storage_kind="env_var",
            value_type="string",
            widget="text",
            write_policy="proposal_only",
            requires_restart=True,
            metadata={"env_key": "AD_LDAP_HOST", "default": ""},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.AD_SERVICE_PASSWORD",
            domain="env",
            section="Active Directory",
            title="AD service password",
            description="Service account password. GUI may propose that it is set, but never displays or stores the raw value.",
            help_topic_id="settings.env.AD_SERVICE_PASSWORD",
            storage_kind="env_var",
            value_type="secret",
            widget="secret",
            write_policy="proposal_only",
            requires_restart=True,
            sensitivity="secret",
            metadata={"env_key": "AD_SERVICE_PASSWORD", "default": ""},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.LOCAL_BUSINESS_AGENT_RUNTIME_URL",
            domain="env",
            section="AI",
            title="Agent runtime URL",
            description="HTTP endpoint for the AI agent runtime used by chat and contextual help.",
            help_topic_id="settings.env.LOCAL_BUSINESS_AGENT_RUNTIME_URL",
            storage_kind="env_var",
            value_type="url",
            widget="text",
            write_policy="proposal_only",
            requires_restart=True,
            metadata={"env_key": "LOCAL_BUSINESS_AGENT_RUNTIME_URL", "default": "http://127.0.0.1:8090"},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.OPENAI_API_KEY",
            domain="env",
            section="AI",
            title="OpenAI API key",
            description="Optional cloud model API key. Store real value only in the private deployment silo or secret vault.",
            help_topic_id="settings.env.OPENAI_API_KEY",
            storage_kind="env_var",
            value_type="secret",
            widget="secret",
            write_policy="proposal_only",
            requires_restart=True,
            sensitivity="secret",
            metadata={"env_key": "OPENAI_API_KEY", "default": ""},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.LOCAL_BUSINESS_SECRET_VAULT_BASE_URL",
            domain="env",
            section="Secrets",
            title="External secret vault URL",
            description="Base URL for Vaultwarden-style external secret links. Raw secrets stay outside portal settings.",
            help_topic_id="settings.env.LOCAL_BUSINESS_SECRET_VAULT_BASE_URL",
            storage_kind="env_var",
            value_type="url",
            widget="text",
            write_policy="proposal_only",
            requires_restart=True,
            metadata={"env_key": "LOCAL_BUSINESS_SECRET_VAULT_BASE_URL", "default": ""},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.MEMORY_ACL_UNRESOLVED_POLICY",
            domain="env",
            section="Memory ACL",
            title="Unresolved memory ACL policy",
            description="Fail-closed policy for unreadable or unmapped file ACLs.",
            help_topic_id="settings.env.MEMORY_ACL_UNRESOLVED_POLICY",
            storage_kind="env_var",
            value_type="choice",
            widget="select",
            write_policy="proposal_only",
            requires_restart=True,
            choices=("block", "admin_only", "fallback_scope_rule"),
            metadata={"env_key": "MEMORY_ACL_UNRESOLVED_POLICY", "default": "block"},
        ),
    ]
