from apps.settings_center.descriptors import SettingDescriptor


def get_settings_descriptors():
    return [
        SettingDescriptor(
            setting_id="core.contract.role_rules",
            domain="core",
            section="Доступ",
            title="Контракт правил ролей",
            description="Рабочие правила возможностей ролей для заявок, навигации и управленческих политик.",
            help_topic_id="settings.core.contract.role_rules",
            storage_kind="runtime_contract",
            value_type="json",
            widget="workflow_transition_matrix",
            write_policy="editable",
            required_permission="settings_center.manage",
            metadata={
                "settings_path": "LOCAL_BUSINESS_ROLE_RULES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_ROLE_RULES",
                "validator": "validate_role_rules_payload",
            },
        ),
        SettingDescriptor(
            setting_id="core.contract.workflow_rules",
            domain="core",
            section="Процессы",
            title="Контракт статусов и переходов",
            description="Рабочие статусы и переходы, которые используются при изменении состояния заявок.",
            help_topic_id="settings.core.contract.workflow_rules",
            storage_kind="runtime_contract",
            value_type="json",
            widget="json_editor",
            write_policy="editable",
            required_permission="settings_center.manage",
            metadata={
                "settings_path": "LOCAL_BUSINESS_WORKFLOW_RULES_FILE",
                "settings_payload_attr": "LOCAL_BUSINESS_WORKFLOW_RULES",
                "validator": "validate_workflow_rules_payload",
            },
        ),
        *env_descriptors(),
    ]


def env_descriptors():
    return [
        SettingDescriptor(
            setting_id="settings_center.env.DJANGO_AUTH_MODE",
            domain="env",
            section="Аутентификация",
            title="Режим входа Django",
            description="Базовый режим аутентификации. Изменение требует перезапуска процесса.",
            help_topic_id="settings.env.DJANGO_AUTH_MODE",
            storage_kind="env_var",
            value_type="choice",
            widget="select",
            write_policy="proposal_only",
            requires_restart=True,
            choices=("local", "ldap", "remote_user", "hybrid"),
            metadata={"env_key": "DJANGO_AUTH_MODE", "default": "hybrid"},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.SETTINGS_CENTER_ENV_APPLY_MODE",
            domain="env",
            section="Центр настроек",
            title="Режим применения настроек окружения",
            description="Определяет, доступны ли настройки окружения только для чтения, через заявки или через локальный файл.",
            help_topic_id="settings.env.SETTINGS_CENTER_ENV_APPLY_MODE",
            storage_kind="env_var",
            value_type="choice",
            widget="select",
            write_policy="proposal_only",
            requires_restart=True,
            choices=("read_only", "proposal", "local_file"),
            metadata={"env_key": "SETTINGS_CENTER_ENV_APPLY_MODE", "default": "proposal"},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.AD_LDAP_HOST",
            domain="env",
            section="Active Directory",
            title="Хост AD LDAP",
            description="Хост контроллера домена для LDAP-поиска и входа пользователей.",
            help_topic_id="settings.env.AD_LDAP_HOST",
            storage_kind="env_var",
            value_type="string",
            widget="text",
            write_policy="proposal_only",
            requires_restart=True,
            metadata={"env_key": "AD_LDAP_HOST", "default": ""},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.AD_SERVICE_PASSWORD",
            domain="env",
            section="Active Directory",
            title="Пароль сервисной учетной записи AD",
            description="Пароль сервисной учетной записи. Интерфейс может создать заявку на установку значения, но не показывает и не хранит сырой секрет.",
            help_topic_id="settings.env.AD_SERVICE_PASSWORD",
            storage_kind="env_var",
            value_type="secret",
            widget="secret",
            write_policy="proposal_only",
            requires_restart=True,
            sensitivity="secret",
            metadata={"env_key": "AD_SERVICE_PASSWORD", "default": ""},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.LOCAL_BUSINESS_AGENT_RUNTIME_URL",
            domain="env",
            section="ИИ",
            title="URL рабочего сервиса агента",
            description="HTTP-адрес рабочего сервиса ИИ-агента, который используется чатом и контекстной справкой.",
            help_topic_id="settings.env.LOCAL_BUSINESS_AGENT_RUNTIME_URL",
            storage_kind="env_var",
            value_type="url",
            widget="text",
            write_policy="proposal_only",
            requires_restart=True,
            metadata={"env_key": "LOCAL_BUSINESS_AGENT_RUNTIME_URL", "default": "http://127.0.0.1:8090"},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.OPENAI_API_KEY",
            domain="env",
            section="ИИ",
            title="API-ключ OpenAI",
            description="Необязательный API-ключ облачной модели. Реальное значение хранится только в приватном контуре развертывания или хранилище секретов.",
            help_topic_id="settings.env.OPENAI_API_KEY",
            storage_kind="env_var",
            value_type="secret",
            widget="secret",
            write_policy="proposal_only",
            requires_restart=True,
            sensitivity="secret",
            metadata={"env_key": "OPENAI_API_KEY", "default": ""},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.LOCAL_BUSINESS_SECRET_VAULT_BASE_URL",
            domain="env",
            section="Секреты",
            title="URL внешнего хранилища секретов",
            description="Базовый URL для внешних ссылок на секреты в стиле Vaultwarden. Сырые секреты остаются вне настроек портала.",
            help_topic_id="settings.env.LOCAL_BUSINESS_SECRET_VAULT_BASE_URL",
            storage_kind="env_var",
            value_type="url",
            widget="text",
            write_policy="proposal_only",
            requires_restart=True,
            metadata={"env_key": "LOCAL_BUSINESS_SECRET_VAULT_BASE_URL", "default": ""},
        ),
        SettingDescriptor(
            setting_id="settings_center.env.MEMORY_ACL_UNRESOLVED_POLICY",
            domain="env",
            section="ACL памяти",
            title="Политика неразрешенных ACL памяти",
            description="Политика закрытого отказа для нечитаемых или несопоставленных файловых ACL.",
            help_topic_id="settings.env.MEMORY_ACL_UNRESOLVED_POLICY",
            storage_kind="env_var",
            value_type="choice",
            widget="select",
            write_policy="proposal_only",
            requires_restart=True,
            choices=("block", "admin_only", "fallback_scope_rule"),
            metadata={"env_key": "MEMORY_ACL_UNRESOLVED_POLICY", "default": "block"},
        ),
    ]
