# Generated by Django 5.2.12 on 2026-05-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analyticsaccessaudit_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssource',
            name='source_kind',
            field=models.CharField(choices=[('memory', 'Memory'), ('django_model', 'Django model'), ('email_imap', 'Email IMAP'), ('file_share', 'File share'), ('dms', 'DMS'), ('external_api', 'External API')], max_length=32),
        ),
    ]
