# Generated by Django 5.2.12 on 2026-05-28 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analyticssource_source_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsaccessaudit',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Аудит доступа к аналитике', 'verbose_name_plural': 'Аудит доступа к аналитике'},
        ),
        migrations.AlterModelOptions(
            name='analyticscase',
            options={'ordering': ['status', '-created_at', '-id'], 'verbose_name': 'Случай аналитики', 'verbose_name_plural': 'Случаи аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticscontentobject',
            options={'ordering': ['source__code', 'source_object_id'], 'verbose_name': 'Объект содержимого аналитики', 'verbose_name_plural': 'Объекты содержимого аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticsdiagnosticrun',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Запуск диагностики аналитики', 'verbose_name_plural': 'Запуски диагностики аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticsduplicatecandidate',
            options={'ordering': ['status', '-created_at', '-id'], 'verbose_name': 'Кандидат-дубликат аналитики', 'verbose_name_plural': 'Кандидаты-дубликаты аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticsevidenceref',
            options={'ordering': ['authority_rank', 'evidence_id'], 'verbose_name': 'Ссылка на доказательство аналитики', 'verbose_name_plural': 'Ссылки на доказательства аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticsextractionpacket',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Пакет извлечения аналитики', 'verbose_name_plural': 'Пакеты извлечения аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticsextractionrun',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Запуск извлечения аналитики', 'verbose_name_plural': 'Запуски извлечения аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticsfact',
            options={'ordering': ['fact_type', '-event_time', '-id'], 'verbose_name': 'Факт аналитики', 'verbose_name_plural': 'Факты аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticsmetriccandidate',
            options={'ordering': ['status', '-created_at', '-id'], 'verbose_name': 'Кандидат метрики аналитики', 'verbose_name_plural': 'Кандидаты метрик аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticsmetricsnapshot',
            options={'ordering': ['metric_code', '-created_at', '-id'], 'verbose_name': 'Снимок метрики аналитики', 'verbose_name_plural': 'Снимки метрик аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticssamplemanifest',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Манифест выборки аналитики', 'verbose_name_plural': 'Манифесты выборок аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticssignal',
            options={'ordering': ['status', '-created_at', '-id'], 'verbose_name': 'Сигнал аналитики', 'verbose_name_plural': 'Сигналы аналитики'},
        ),
        migrations.AlterModelOptions(
            name='analyticssource',
            options={'ordering': ['code'], 'verbose_name': 'Источник аналитики', 'verbose_name_plural': 'Источники аналитики'},
        ),
        migrations.AlterField(
            model_name='analyticscase',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('routed', 'Маршрутизирован'), ('in_progress', 'В работе'), ('resolved', 'Закрыт'), ('cancelled', 'Отменен')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='analyticsdiagnosticrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('succeeded', 'Завершен'), ('failed', 'Ошибка')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='analyticsduplicatecandidate',
            name='status',
            field=models.CharField(choices=[('proposed', 'Предложен'), ('merged', 'Объединен'), ('versioned', 'Версионирован'), ('rejected', 'Отклонен')], default='proposed', max_length=16),
        ),
        migrations.AlterField(
            model_name='analyticsextractionrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('succeeded', 'Завершен'), ('failed', 'Ошибка'), ('cancelled', 'Отменен')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='analyticsmetriccandidate',
            name='status',
            field=models.CharField(choices=[('proposed', 'Предложен'), ('needs_review', 'Требует проверки'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='proposed', max_length=32),
        ),
        migrations.AlterField(
            model_name='analyticssignal',
            name='severity',
            field=models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('high', 'Высокая'), ('critical', 'Критическая')], default='warning', max_length=16),
        ),
        migrations.AlterField(
            model_name='analyticssignal',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('diagnosing', 'Диагностика'), ('routed', 'Маршрутизирован'), ('resolved', 'Закрыт'), ('ignored', 'Игнорируется')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='analyticssource',
            name='source_kind',
            field=models.CharField(choices=[('memory', 'Память'), ('django_model', 'Модель Django'), ('email_imap', 'Почта IMAP'), ('file_share', 'Файловый ресурс'), ('dms', 'DMS'), ('external_api', 'Внешний API')], max_length=32),
        ),
        migrations.AlterField(
            model_name='analyticssource',
            name='status',
            field=models.CharField(choices=[('enabled', 'Включен'), ('disabled', 'Отключен'), ('error', 'Ошибка')], default='enabled', max_length=16),
        ),
    ]
