# Generated by Django 5.2.12 on 2026-06-15 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_analyticsaccessaudit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsaccessaudit',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_access_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analyticsdiagnosticrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_diagnostic_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analyticsduplicatecandidate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_duplicate_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analyticsextractionrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_extraction_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analyticsmetriccandidate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='analytics_metric_candidate_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
