# Generated by Django 5.2.12 on 2026-06-03 09:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Идентификатор события')),
                ('event_type', models.CharField(max_length=120, verbose_name='Тип события')),
                ('source_app', models.CharField(max_length=64, verbose_name='Приложение-источник')),
                ('source_object_type', models.CharField(max_length=80, verbose_name='Тип объекта')),
                ('source_object_id', models.CharField(max_length=120, verbose_name='Идентификатор объекта')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('body', models.CharField(blank=True, max_length=240, verbose_name='Текст')),
                ('target_url', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('severity', models.CharField(choices=[('info', 'Обычное'), ('warning', 'Важное'), ('critical', 'Критичное')], default='info', max_length=16, verbose_name='Важность')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Событие уведомления',
                'verbose_name_plural': 'События уведомлений',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_d4510d_idx'), models.Index(fields=['source_app', 'source_object_type', 'source_object_id'], name='notificatio_source__b2c279_idx'), models.Index(fields=['severity', '-created_at'], name='notificatio_severit_930c34_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationBrowserClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_fingerprint_hash', models.CharField(max_length=96, verbose_name='Хеш браузера')),
                ('user_agent_family', models.CharField(blank=True, max_length=120, verbose_name='Браузер')),
                ('notification_permission', models.CharField(choices=[('default', 'Не запрошено'), ('granted', 'Разрешено'), ('denied', 'Запрещено')], default='default', max_length=16, verbose_name='Разрешение уведомлений')),
                ('enabled', models.BooleanField(default=False, verbose_name='Включено на устройстве')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_browser_clients', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Браузерный клиент уведомлений',
                'verbose_name_plural': 'Браузерные клиенты уведомлений',
                'ordering': ['-last_seen_at', '-id'],
                'indexes': [models.Index(fields=['user', '-last_seen_at'], name='notificatio_user_id_162b8e_idx'), models.Index(fields=['notification_permission', '-last_seen_at'], name='notificatio_notific_a87f32_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'browser_fingerprint_hash'), name='notifications_browser_client_user_hash_uniq')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=160, verbose_name='Название устройства')),
                ('platform', models.CharField(max_length=64, verbose_name='Платформа')),
                ('token_hash', models.CharField(max_length=128, unique=True, verbose_name='Хеш токена')),
                ('scopes', models.JSONField(blank=True, default=list, verbose_name='Права')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен устройства уведомлений',
                'verbose_name_plural': 'Токены устройств уведомлений',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'revoked_at'], name='notificatio_user_id_ffddd2_idx'), models.Index(fields=['platform', '-created_at'], name='notificatio_platfor_ec86cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'В портале'), ('browser', 'Браузер'), ('desktop', 'Настольное приложение')], max_length=32, verbose_name='Канал')),
                ('event_type', models.CharField(default='*', max_length=120, verbose_name='Тип события')),
                ('enabled', models.BooleanField(default=True, verbose_name='Включено')),
                ('min_severity', models.CharField(choices=[('info', 'Обычное'), ('warning', 'Важное'), ('critical', 'Критичное')], default='info', max_length=16, verbose_name='Минимальная важность')),
                ('quiet_hours', models.JSONField(blank=True, default=dict, verbose_name='Тихие часы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
                'ordering': ['channel', 'event_type'],
                'indexes': [models.Index(fields=['user', 'channel'], name='notificatio_user_id_016cb8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel', 'event_type'), name='notifications_pref_user_channel_event_uniq')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('new', 'Новое'), ('seen', 'Просмотрено'), ('read', 'Прочитано'), ('dismissed', 'Скрыто')], default='new', max_length=16, verbose_name='Состояние')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено клиенту')),
                ('seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Просмотрено')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('dismissed_at', models.DateTimeField(blank=True, null=True, verbose_name='Скрыто')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notificationevent', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipients', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Получатель уведомления',
                'verbose_name_plural': 'Получатели уведомлений',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['user', '-id'], name='notificatio_user_id_1deca1_idx'), models.Index(fields=['user', 'state', '-id'], name='notificatio_user_id_c6ff5b_idx'), models.Index(fields=['state', '-created_at'], name='notificatio_state_7d78bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='notifications_event_user_uniq')],
            },
        ),
    ]
