# Generated by Django 5.2.12 on 2026-06-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeviceLinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, unique=True, verbose_name='Хеш кода')),
                ('device_name', models.CharField(blank=True, max_length=160, verbose_name='Название устройства')),
                ('platform', models.CharField(blank=True, max_length=64, verbose_name='Платформа')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_device_link_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код подключения устройства',
                'verbose_name_plural': 'Коды подключения устройств',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_c1a9e8_idx'), models.Index(fields=['expires_at', 'used_at'], name='notificatio_expires_80a785_idx')],
            },
        ),
    ]
